### PR TITLE
Dockerfiles to use nargo inside of a container

### LINKED ISSUE #282: Must run bootstrap script inside barretenberg after updating commit reference in aztec backend crate
When the commit reference to the aztec backend is updated, simply installing nargo by itself currently fails. In this [PR](https://github.com/noir-lang/noir/pull/274) the insert merkle opcode was deleted which required changes to the barretenberg serialization. The commit reference was [updated](https://github.com/noir-lang/noir/pull/274/files#diff-783445433661113a3a3da2d566388eb68952c56418d572ee3a1ec2ec81f2f338L12) to reflect this change. However, when running `cargo install --locked --path=.` inside nargo the backend would fail to build. 

```  --- stderr
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS


  make: warning: -jN forced in submake: disabling jobserver mode.
  CMake Error at /usr/local/Cellar/cmake/3.23.1/share/cmake/Modules/GoogleTestAddTests.cmake:112 (message):
    Error running test executable.

      Path: '/Users/maximvezenov/Documents/dev/noir/target/release/build/barretenberg_wrapper-e5a5dbe1119d7c88/out/build/src/aztec/dsl/dsl_tests'
      Result: Process terminated due to timeout
      Output:
        

  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.23.1/share/cmake/Modules/GoogleTestAddTests.cmake:225 (gtest_discover_tests_impl)


  make[2]: *** [src/aztec/dsl/dsl_tests] Error 1
  make[2]: *** Deleting file `src/aztec/dsl/dsl_tests'
  make[1]: *** [src/aztec/dsl/CMakeFiles/dsl_tests.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  make: *** [all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2

  build script failed, must exit now', /Users/maximvezenov/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The build would succeed upon checking out to the relevant commit in barretenberg and running the bootstrap script. I am on an intel so to be specific I ran `./bootstrap.sh APPLE_INTEL`. barretenberg then successfully built and I successfully installed nargo. 

Rerunning `bootstrap.sh` in barretenberg is also needed when trying to install `nargo` after a `cargo clean`

It seems that a developer should be able to build nargo without having to install the barretenberg repo themselves and subsequently run the bootstrap script. I am curious if anyone else has experienced this issue as well.

### PR DESCRIPTION
**Pull request by vezenovm**
# Related issue(s)

(If it does not already exist, first create a GitHub issue that describes the problem this Pull Request (PR) solves before creating the PR and link it here.)

Resolves #282 and many other `nargo` installation issues that are persistent among users. 

# Description

This PR contains the Dockerfile setup used to generate the images currently stored in my personal Docker account `maximaztec`. These should be moved to a shared `noir-lang` Dockerhub where we place images to be released to the public. This solution should be seen as a "last resort" for building nargo. If a developer wants to use `nargo` but cannot build it on their local machine, the images provided by us will allow them to use an already prebuilt nargo inside of a container. 

You can test out running the image right now with 
`docker run -it maximaztec/noir`

If you would like to build the images yourself locally you can follow the commands below:
`docker build -f Dockerfile.env --tag noir-env .`
`docker build --tag noir .`
`docker run -it noir`

Once inside the container you can run `cd $NARGO_HOME` where I have placed all the nargo examples for testing. We don't have to store all of these examples in the image either, but I just copied over the whole folder for now as new images are going to have be published under the `noir-lang` Docker hub either way. 

## Summary of changes

This PR simply aims to add two Dockerfiles. One is `Dockerfile.env` that installs all the necessary dependencies for building `barretenberg` as well as `cargo`. `Dockerfile` then uses this env image to build `nargo` and places it into a fresh ubuntu container. 

Inspiration was taken from [Zokrates](https://github.com/Zokrates/ZoKrates/blob/develop/Dockerfile). I had some issues while constructing the Dockerfile, and after making fixes everything looked very similar to what Zokrates had already done. I then used their files as a reference and also took inspiration from them for splitting up the environment and final build. The `noir-env` image ended up being around 1.8GB. While the `noir` image is `148MB`. We should make sure to credit Zokrates either in our docs, in the comments of the Dockerfile, or both. 

The size of the `noir` image should ideally be much smaller as well. Switching to alpine linux from ubuntu would lead to a large reduction in the image size, however, I was continuously running into errors with linking when trying to build using alpine ("error: linking with `cc` failed: exit code: 1"). 

## Dependency additions / changes

(If applicable.)

## Test additions / changes

(If applicable.)

# Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [X] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [X] I have reviewed the changes on GitHub, line by line.
- [X] I have ensured all changes are covered in the description.

# Additional context

We should possibly reconsider how we are downloading/handling the SRS. Perhaps in addition to downloading the SRS when proving, we could also provide a separate command to download the SRS entirely separately from nargo. This would allow the docker container to mount a read only volume where the SRS is located on a user's local machine. Currently, the SRS is downloaded inside the container upon the first usage of `nargo prove`. This seems redundant and we should be able to reuse an SRS that exists on a user's local machine.

### CODE REVIEW

**Comment by jfecher** [comment]
Seems like this is not a catch-all solution. Running `nargo prove p` with a small sample program on my M1 mac fails with `qemu: uncaught target signal 4 (Illegal instruction) - core dumped`

**Comment by vezenovm** [comment]
> Seems like this is not a catch-all solution. Running `nargo prove p` with a small sample program on my M1 mac fails with `qemu: uncaught target signal 4 (Illegal instruction) - core dumped`

Looks like we may need an ARM docker image. I am going to look into doing a multi arch Docker build. But if takes up a lot of time and @kobyhallx makes more progress with Nix, perhaps it can be avoided.

**Comment by Globallager** [comment]
Got a `qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory` on my M2 Mac:
image

Steps to reproduce:
1. `docker run -it maximaztec/noir`
2. `nargo`

**Comment by kevaundray** [comment]
Closing for now as we now have binaries

**Pull request closed without merging**
