### PR TITLE
feat: Execute brillig opcodes with constant inputs at compile-time

### LINKED ISSUE #2189: Execute any `Brillig` opcodes which have constant inputs at compile time
### Problem

The `brillig_integer_binary_operations` integration test has zero arguments so should be able to be compiled down to an empty circuit. However, because of our usage of brillig opcodes we have 43 gates which need to be handled by the backend.

This is low-hanging fruit for compiler optimisation.

### Happy Case

When performing ACIR gen on brillig opcodes we should check to see if all of the inputs are known constants. If so then we should execute the brillig opcode within the compiler and return constant `AcirVar`s for the opcode outputs. This will allow us to use these values to perform later optimisations.

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #2189 

## Summary\*

This PR executes any Brillig opcodes for which all of the inputs are known at compile time so that we can just create constants for the results to inject where necessary. This allows us to completely solve some test circuits at compile time.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
Would this still be needed if we only translated the SSA -> Brillig after performing the SSA optimizations? I believe this is something we wanted to do anyway.

**Comment by TomAFrench** [comment]
I'm not sure however it's pretty self contained so we could always remove it once that's implemented.

https://github.com/noir-lang/noir/issues/2066

**Comment by TomAFrench** [comment]
Bumping this.

**Review by sirasistant — DISMISSED** [review]
LGTM, could you add a comment pointing to the issue of applying optimizations before brillig gen so we remove this optimization in acir_gen after that issue is done?

**Review by kevaundray — APPROVED** [review]

**Pull request merged**
