### PR TITLE
fix(ssa refactor): Ignore array out of bounds errors when enable_side_effects is false

### LINKED ISSUE #1629: Test named `sha2_byte` crashes during compliation
### Aim

Test named `sha2_byte` should compile

### Expected Behavior

^

### Bug

It appears to hang during the cfg flatten pass.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

When `enable_side_effects` is false, we are meant to be in a false branch of an `if` that was not taken, so we should ignore side effects causing the program to fail, such as array out of bounds errors. I've added a check for this to only panic for array index of out of bounds errors if enable side effects is not known to be false.

This fixes the bug in #1629 ~~but means the issue will still appear if the `if` uses a witness as its condition, as it would not be known to be false.~~ I've changed the logic to only panic if `enable_side_effects` is known to be true rather than not known to be false.

Resolves #1629 

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by ludamad** [comment]
Hmm interesting problem, longer term we may have to ignore even more array out of bounds I guess you're implying? LGTM

**Review by ludamad — DISMISSED** [review]

**Comment by ludamad** [comment]
Cool that change makes sense to me

**Review by ludamad — APPROVED** [review]

**Comment by ludamad** [comment]
Maybe a comment about the logic that led here? Probably surprising that it's usually ignored at first read

**Comment by ludamad** [comment]
Also now I guess we want an issue for infrastructure for detecting if both sides would have an error, possibly a conservative setting that doesn't allow an error on either side but that I'm more speculative on

**Comment by jfecher** [comment]
> detecting if both sides would have an error, possibly a conservative setting that doesn't allow an error on either side but that I'm more speculative on

What do you mean by both sides here?

**Comment by ludamad** [comment]
> 

Deleted that comment, thought this came up more generally

**Pull request merged**
