### PR TITLE
chore: Experimenting with stepwise ACVM solver [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves 

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
I'm getting failures on the program

```rust
use dep::std;

fn main(x: Field, y: Field, salt: Field, out_x: Field, out_y: Field ) {
    // let res = std::hash::pedersen([x, y]);
    // assert(res[0] == out_x);
    // assert(res[1] == out_y);

    let raw_data = [x,y];
    let mut state = 0;
    for i in 0..2 {
        state = state * 8 + raw_data[i];
    }
    state += salt;
    let hash = std::hash::pedersen([state]);
    // assert(std::hash::pedersen([43])[0] == hash[0]);
}   
```

Which results in the ACIR (pre/post optimization)

```
Unoptimised ACIR for main:
current witness index : 8
public parameters indices : []
return value indices : []
EXPR [ (8, _1) (1, _2) (1, _3) (-1, _6) 0 ]
BLACKBOX::PEDERSEN [(_6, num_bits: 254)] [ _7, _8] domain_separator: 0

Compiled ACIR for main:
current witness index : 11
public parameters indices : []
return value indices : []
EXPR [ (1, _3) (-1, _6) (-1, _10) 0 ]
EXPR [ (8, _1) (1, _2) (1, _10) 0 ]
BLACKBOX::PEDERSEN [(_6, num_bits: 254)] [ _7, _8] domain_separator: 0
```

Looks like it's running into the issue of not knowing how to sort the arithmetic opcodes. I purposefully removed this sorting [here](https://github.com/noir-lang/acvm/pull/399/commits/9810b460dba878204e2ed3d4795b940883c2031b) as it results in the bad outcome as described in https://github.com/noir-lang/acvm/pull/419

**Comment by kevaundray** [comment]
@TomAFrench Is this still a [DO NOT MERGE] PR or will this be used for introducing stepwise execution?

**Comment by TomAFrench** [comment]
I'll probably repurpose this PR but for now it's a scratch branch while I get dynamic arrays working.

**Comment by TomAFrench** [comment]
Closing in favour of #2051

**Pull request closed without merging**
