### PR TITLE
feat(nargo): Implement nargo clean

### PR DESCRIPTION
**Pull request by Ethan-000**
# Description

## Problem\*

Resolves https://github.com/noir-lang/noir/issues/1691

## Summary\*

implement a new nargo cli feature that allow devs to conveniently remove crs data/nargo cache and target directory

## Documentation

- [x] This PR requires documentation updates when merged.

  

  - [x] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by kevaundray** [comment]
@TomAFrench can this PR be merged?

**Review by jfecher — APPROVED** [review]
LGTM, just need to fix an import

**Comment by phated** [comment]
The nargo tooling team is discussing where artifacts should live, so I'm marking this as a draft right now.

**Comment by jfecher** [comment]
What is the status on this PR? Can we update it to fix the merge conflicts?

**Comment by Ethan-000** [comment]
i can try to fix it if this functionality is desired

**Pull request closed without merging**
