### PR TITLE
chore(ssa refactor): Rename Brillig example

### PR DESCRIPTION
**Pull request by kevaundray**
# Description

Naming the example "Brillig" is too ambiguous and does not tell us what it is testing 

## Problem\*

Resolves 

## Summary\*

This PR sets out to

### Example

Before:

```

```

After:

```

```

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by guipublic — CHANGES_REQUESTED** [review]
That was done on purpose, the idea is to have one test which focus on brillig, rather than a specific test for the brillig identity function.

Why this is better?
Having several tests in one test file is good because it reduces a lot the duration of the tests and so it improves the CI performance.

However, iInside the test file, we should comment appropriately what each unit test is doing.

**Comment by kevaundray** [comment]
Having several tests in one file makes it harder to debug which test failed and or whether we are regressing anything.

In the future, we may want to turn some or all of these small tests into unit tests instead of end-to-end, though right now as with acir gen, we have a test file for each milestone

**Comment by guipublic** [comment]
No, it does not impact on regression, since the tests even if they are grouped in one file, are still here.
It does however makes it harder to see which test is failing, but it's easy to figure out.

**Comment by kevaundray** [comment]
> No, it does not impact on regression, since the tests even if they are grouped in one file, are still here.
> It does however makes it harder to see which test is failing, but it's easy to figure out.

The impact will be that with separate files, the CI will tell you that `prove_and_verify_simple_identity_function has failed` wheras with one file, the CI will tell you that `prove_and_verify_brillig has failed`

**Review by ludamad — APPROVED** [review]

**Pull request merged**
