### PR TITLE
fix: decode databus return values

### LINKED ISSUE #5715: NoirJS doesn't report return values when doing witness gen on a function with databus (return_data)
### Aim

Get the return values along with the witness when calling a function with return_data, to pass them to the next circuit in the IVC chain.

### Expected Behavior

As the prover entity, I should be able to get the databus return_data to pass it to the next circuit for recursive verification.

### Bug

They are not due to this line https://github.com/noir-lang/noir/blob/master/tooling/noirc_abi/src/lib.rs#L351

### To Reproduce

1. Create a noir circuit with return_data
2. Call it via noirjs

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #5715

## Summary\*

This PR picks up from @guipublic's work on #6074 to enable decoding databus return values in `noirc_abi`. I've added a test to show this working

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
@guipublic Can you take a look at this?

**Review by guipublic — CHANGES_REQUESTED** [review]
Either we write the databus return values like it is done in this PR, and then I think we need to re-work noirc_abi/lib.rs:
- has_public_inputs() should only test for public parameter
- encode() may need (I'm not completely sure) to specify return_data or public for the return value, or at least change the comment about the verifier.
And we should also change the prover so that the 'databus' return values are not added to the proof as public inputs.

Or we do not, and the prover can use the witness index of the return values in the ABI to recover them from the witness map.

**Comment by TomAFrench** [comment]
Thanks, I've updated `has_public_inputs`.

Although I'm not clear on your second point. We shouldn't need to update the `encode` function afaik and the databus return values are not added to the public inputs (the ABI doesn't specify this but it's embedded in the circuit.)

**Comment by guipublic** [comment]
I just tried and I think I am getting public inputs in the proof, but we can say that it's a prover issue, as long as it can get the required info, which is the ABI, so it's fine.

**Review by guipublic — APPROVED** [review]

**Pull request merged**
