### PR TITLE
fix(ssa refactor): resolve replaced value ids for printing

### LINKED ISSUE #1451: (SSA Refactor) Printer prints old ValueId after `set_value` is called
### Aim

Running the mem2reg pass on the code:
```
fn main f0 {
  b0(v0: u1, v1: u1):
    v2 = alloc 1 fields
    store Field 0 at v2
    v7 = load v2
    call println(Field 0, v7)
    store Field 1 at v2
    v40 = load v2
    call println(Field 1, v40)
    v42 = load v2
    store Field 2 at v2
    v43 = load v2
    call println(Field 2, v43)
    v44 = load v2
    call println(Field 4, v44)
    v45 = and v0, v1
    v47 = load v2
    store Field 5 at v2
    v48 = load v2
    call println(Field 5, v48)
    v49 = not v1
    v50 = and v0, v49
    v52 = load v2
    store Field 6 at v2
    v53 = load v2
    call println(Field 6, v53)
    v54 = mul v1, Field 5
    v55 = mul v49, v47
    v56 = add v54, v55
    store v56 at v2
    v57 = mul v1, v52
    v58 = mul v49, Field 6
    v59 = add v57, v58
    store v59 at v2
    v60 = load v2
    call println(Field 7, v60)
    v61 = not v0
    v63 = load v2
    store Field 3 at v2
    v64 = load v2
    call println(Field 3, v64)
    v65 = load v2
    call println(Field 8, v65)
    v66 = mul v0, v59
    v67 = mul v61, v42
    v68 = add v66, v67
    store v68 at v2
    v69 = mul v0, v63
    v70 = mul v61, Field 3
    v71 = add v69, v70
    store v71 at v2
    v72 = load v2
    call println(Field 9, v72)
    return 
}
```

### Expected Behavior

The mem2reg pass should replace all known stores with the known values and leave stores that are unknown. Failing that, the pass should at least leave the program in a valid state.

### Bug

The actual SSA returned by the mem2reg pass is:
```
fn main f0 {
  b0(v0: u1, v1: u1):
    v2 = alloc 1 fields
    store Field 0 at v2
    call println(Field 0, Field 0)
    store Field 1 at v2
    call println(Field 1, Field 1)
    store Field 2 at v2
    call println(Field 2, Field 2)
    call println(Field 4, Field 2)
    v45 = and v0, v1
    store Field 5 at v2
    call println(Field 5, Field 5)
    v49 = not v1
    v50 = and v0, v49
    store Field 6 at v2
    call println(Field 6, Field 6)
    v54 = mul v1, Field 5
    v55 = mul v49, Field 2
    v56 = add v54, v55
    store v56 at v2
    v57 = mul v1, Field 5
    v58 = mul v49, Field 6
    v59 = add v57, v58
    store v59 at v2
    call println(Field 7, v60)
    v61 = not v0
    store Field 3 at v2
    call println(Field 3, Field 3)
    call println(Field 8, Field 3)
    v66 = mul v0, v59
    v67 = mul v61, Field 1
    v68 = add v66, v67
    store v68 at v2
    v69 = mul v0, v63
    v70 = mul v61, Field 3
    v71 = add v69, v70
    store v71 at v2
    call println(Field 9, v72)
    return 
}
```
Note `v60` which is referenecd by `call println(Field 7, v60)` but there is no corresponding definition for `v60`.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by joss-aztec**
# Description

## Problem\*

The SSA printer gave confusing output when a value had been replaced (during mem2reg).

Resolves #1451

## Summary\*

Track ids involved in value replacements such that the printer can resolve them later.

For program:

```rs
fn main(x: Field) -> pub Field {
    let xs = [x];
    xs[0]
}
```

Before:

```
fn main f1 {
  b0(v0: Field):
    v1 = alloc 1 fields
    return v2
}
```

After:

```
fn main f1 {
  b0(v0: Field):
    v1 = alloc 1 fields
    return v0
}
```

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
It may be the case we should remove `set_value` and `set_value_from_id` entirely. Instead we'd have to manually find each instruction that references the value and mutate that instruction.

Alternatively, if we want to keep `set_value`, we'd have to avoid `HashMap<ValueId, _>` entirely and switch to e.g. `HashMap<Value, _>` directly. Or switch ValueId to be the equivalent of a `Value**` rather than a `Value*`.

**Comment by joss-aztec** [comment]
I'm more incline to remove `set_value` and `set_value_from_id`. It would be awkward when substitution is required, but I'd rather have to deal with that awkwardness in a contained manner, than have to introduce the extra mental overhead of thinking in terms of pointers to pointers everywhere else.

**Comment by joss-aztec** [comment]
Added issue for tracking: https://github.com/noir-lang/noir/issues/1592

**Review by jfecher — APPROVED** [review]
Merging this PR should fix the issue with set_value, but getting the acir_gen tests working also requires PR #1595 to remove the remaining allocate instructions. That PR will need the fix provided from this PR as well.

**Pull request merged**
