### PR TITLE
feat: Implement generic traits

### LINKED ISSUE #3471: Support generic traits
### Problem

While generics on trait methods and trait impls on generic types are working, generics on traits directly are not supported yet.

### Happy Case

The following should execute successfully:
```rs
trait Into<Result> {
    fn into(self) -> Result;
}

impl Into<u32> for Field {
    fn into(self) -> u32 {
        self as u32
    }
}

impl Into<u64> for Field {
    fn into(self) -> u64 {
        self as u64
    }
}
```

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### LINKED ISSUE #3474: Traits should allow methods with generic return types
### Aim

Currently it is possible to use generics within a trait:

```rust
trait Extensions
{
    fn generic<N>(self : [u8], right : [u8; N]) -> bool;   // OK
}
```

### Expected Behavior

A trait allows methods with a generic _return_ type:

```rust
trait Extensions
{
    fn generic<N>(self) -> [u8; N];                    
}
```

### Bug

When creating the implementation the compiler throws a confusing error:

```rust
impl Extensions for [u8]
{
    pub fn generic<N>(self) -> [u8; N] // error: Expected type [u8; N], found type [u8; N]
    {
        // .. //
    }
}
```

Linked issue: https://github.com/noir-lang/noir/issues/3502

### To Reproduce

Compile the following:

```rust
trait Extensions
{
    fn generic<N>(self) -> [u8; N];                    
}

impl Extensions for [u8]
{
    pub fn generic<N>(self) -> [u8; N] // error: Expected type [u8; N], found type [u8; N]
    {
        // .. //
    }
}
```

### Installation Method

Binary

### Nargo Version

0.19.2

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #3471
Resolves #3474

## Summary\*

Implements support for generics on the trait directly. E.g. `trait Into<T> { ... }`

## Additional Context

The old `trait_generics` test has been renamed to `trait_impl_generics` - I think this is more accurate. There is a new test in `trait_generics` now which tests the generic traits added by this PR.

I've discovered two new bugs in writing this PR, which are commented in the `trait_generics` test. I'll make issues for them now.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [x] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
Issue/PR #4000 🎉

**Comment by jfecher** [comment]
Ah, forgot to update some code I commented out. PR is not done yet, apologies.

**Comment by Thunkar** [comment]
Just checked to avoid duplicating work. This fixes https://github.com/noir-lang/noir/issues/3474 !

**Comment by jfecher** [comment]
@Thunkar I didn't finish rewriting the check for the parameters / return type of a trait method yet at the time. I tested again after fixing the `trait_impl_generics` test and #3474 is fixed now in this PR

**Comment by jfecher** [comment]
@kevaundray @TomAFrench @vezenovm, this PR is ready to review again

**Comment by sirasistant** [comment]
One question, this fails on me with the code in this PR:
```rust
trait Serializable<N> {
    fn serialize(self) -> [Field; N];
}

global DATA_LEN = 2;

struct Data {
    a: Field,
    b: Field,
}

impl Serializable<DATA_LEN> for Data {
    fn serialize(self) -> [Field; DATA_LEN] {
        [self.a, self.b]
    }
}

fn sum<T, N>(data: T) -> Field where T: Serializable<N> {
    let serialized = data.serialize();
    serialized.fold(0, |acc, elem| acc + elem)
}

fn main(data: Data) -> pub Field {
    sum(data)
}

```
It generates invalid SSA:
```
Initial SSA:
acir fn main f0 {
  b0(v0: Field, v1: Field):
    v3 = call f1(v0, v1)
    return v3
}
acir fn sum f1 {
  b0(v0: Field, v1: Field):
    v3, v4 = call f2(v0, v1)
    inc_rc v4
    inc_rc v4
    v8 = call f3(v3, v4, Field 0, f4)
    return v8
}
acir fn serialize f2 {
  b0(v0: Field, v1: Field):
    return [v0, v1]
}
acir fn fold f3 {
  b0(v0: Field, v1: [Field], v2: Field, v4: function):
    v3 = allocate
    store v2 at v3
    inc_rc v1
    inc_rc v1
    jmp b1(Field 0)
  b1(v5: Field):
    v8 = lt v5, v0
    jmpif v8 then: b2, else: b3
  b2():
    v10 = cast v0 as u64
    v11 = lt v5, v10
    constrain v11 == u1 1 'Index out of bounds'
    v13 = array_get v1, index v5
    v14 = load v3
    v15 = call v4(v14, v13)
    store v15 at v3
    v16 = add v5, Field 1
    jmp b1(v16)
  b3():
    v17 = load v3
    return v17
}
acir fn lambda f4 {
  b0(v0: Field, v1: Field):
    v2 = add v0, v1
    return v2
}

```
It thinks that serialize returns a slice instead of a fixed length array

**Comment by jfecher** [comment]
Thanks for the test @sirasistant, it turned out to be a very good one since it highlighted a lot of requirements I hadn't yet done. I had thought I was missing something since the original PR was quite small, and indeed I was missing a lot. I also thought the `Into<T>` test was sufficient, but your example highlights the need to test more. I added your example as a test, and added a variant of it where the trait method is called with a static method which gave me some additional issues while testing that are resolved now.

This PR should be ready for review now.

**Review by kevaundray — APPROVED** [review]

**Pull request merged**
