### PR TITLE
fix(nargo): Update acvm-backend-barretenberg to allow wasm backend compilation

### PR DESCRIPTION
**Pull request by phated**
# Description

## Problem\*

Resolves 

## Summary\*

This updates acvm-backend-barretenberg to a version that removes the wasm32 target. There seems to be conflicting dependencies between the backend and the `noir_wasm` crate. Since we aren't going to target wasm32 target with the backend, we can just remove it.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by kevaundray** [comment]
Somewhat related to this PR; perhaps this allows us to remove the hack that was placed here: https://github.com/noir-lang/noir/blob/e449b924e0baf2f6e34b36d182da3979cd1276ee/crates/wasm/Cargo.toml#L27

Not needed for this PR, just wanted to flag it

**Comment by phated** [comment]
> Somewhat related to this PR; perhaps this allows us to remove the hack that was placed here:

I'll try removing it. Might as well land that chore here if it isn't needed anymore.

**Comment by phated** [comment]
`getrandom` workaround still needs to exist. The reason for this is similar to the reason we had to remove the wasm32 target in the backend: the noir_wasm crate is being built by cargo in the workspace, but it really should only be built by wasm-bindgen since it is not made to target anything but wasm32

**Review by kobyhallx — APPROVED** [review]
👍

**Pull request merged**
