### PR TITLE
feat(acir_gen): Use predicates with MemoryOps

### LINKED ISSUE #2133: Noir program attempts to read uninitialised memory
Reopening @ax0's issue #2099 based on the new error.

### Aim

Generate a proof for [this program](https://github.com/aragonzkresearch/noir-trie-proofs/tree/main/tests/depth_8_storage_proof).

### Expected Behavior

A proof is successfully generated.

### Bug

We get the following error:
```
$ nargo execute
The application panicked (crashed).
Message:  Should not read uninitialized memory
Location: /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/acvm-0.21.0/src/pwg/memory_op.rs:26

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### To Reproduce

1. `git clone https://github.com/aragonzkresearch/noir-trie-proofs`
2. `cd noir-trie-proofs/tests/depth_8_storage_proof`
3. `nargo execute`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.9.0 (git version hash: a07b8a48924865d8425d35e40c75f48a13a81935, is dirty: false)

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #2133 

## Summary\*

The ACVM was missing a predicate as part of MemoryOps, thus we were pushing MemoryOps in ACIR gen without their predicate. This caused memory operations under dynamic predicates to be executed no matter what. This is a bug as we can error out with an index out of bounds for valid execution. The linked issue has a full example of this and I have expanded the `dynamic_index_failure` test:

```rust
fn main(mut x: [u32; 5], z: Field) {
    let idx = z + 10;
    
    if z == 20 {
        x[0] = x[4];
    } else {
        // We should not hit out of bounds here as we have a predicate
        // that should not be hit
        if idx as u32 < 3 {
            x[idx] = 10;
        }
    }
    // Error should occur here as an index out of bounds read occurs 
    assert(x[idx] != 0);
}
```

Patches:
Backend branch: https://github.com/noir-lang/acvm-backend-barretenberg/pull/247
ACVM: https://github.com/noir-lang/acvm/pull/503

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
Waiting to review this until the other PR is merged

**Review by TomAFrench — CHANGES_REQUESTED** [review]
This is currently using a patched ACVM and should not be merged until we've included the changes in a release.

**Comment by vezenovm** [comment]
This PR was originally created to avoid the execution error in ACVM with mem ops and predicates. This should be superseded by https://github.com/noir-lang/noir/issues/2493. As per https://github.com/noir-lang/noir/issues/2493#issuecomment-1701326747 we should be able to then remove the inclusion of a predicate on the MemoryOp ACIR opcode as well.

**Comment by vezenovm** [comment]
Superseded by https://github.com/noir-lang/noir/pull/2553

**Pull request closed without merging**
