### PR TITLE
chore(docs): adding quick reference to oracles, guide and explainer to follow

### LINKED ISSUE #3971: Document the `#[oracle]` attribute
### Problem

The `#[foreign_call]` attribute has been surfaced in multiple discussions as a feature for fetching information outside of the Noir program, but we don't currently have written explanations of how it is used.

### Happy Case

Document how is `#[foreign_call]` used in the Noir docs with examples.

### Alternatives Considered

_No response_

### Additional Context

Non-exhausive / potentially inaccurate list of reference PRs I came across:
- https://github.com/noir-lang/noir/pull/3294
- https://github.com/noir-lang/noir/pull/3506
- https://github.com/noir-lang/noir/pull/3764
- https://github.com/noir-lang/noir/pull/3902

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by signorecello**
# Description

Adds almost a "dummy" page on Oracles to the reference section (here called "concepts" due to the almost inevitable mix between explanations and language reference)

## Problem\*

Closes #3971 

## Summary\*

- Adds an "oracles" page to the concepts section simply explaining how to use the flag and mentioning the RPC server. Intentionally, there is no info on how to write the RPC server and how to pass it to the oracle function, as that falls outside of the scope of the language, and thus should be part of a how-to guide
- Updates sibebar item order and adds it to Traits. This is mostly unecessary but for the time being we can totally manage them and profit from controlling sidebar ordering

## Additional Context

We can almost consider this 1/3 of the work, so I'm glad making it a draft now and add it to a bigger PR with the guide/explainer. Just wanted to close #3971 for the time being

### CODE REVIEW

**Comment by Savio-Sou** [comment]
> part of a how-to guide
That's going into the "How To Guides" section of the docs right?

In that case would prefer closing https://github.com/noir-lang/noir/issues/3971 when we have the guide ready for merging instead.

(Feel free to update the original Issue for better alignment with the diátaxis framework if need to.)

**Comment by TomAFrench** [comment]
tbh, this seems to give just enough information to entice extra questions on this topic without allowing users to actually use these. This is probably counterproductive in terms of saving time spent helping people use oracles

**Comment by signorecello** [comment]
Agreed! Making it a draft and reusing this branch for the rest of it

**Comment by signorecello** [comment]
Superseeded by #4002

**Pull request closed without merging**
