### PR TITLE
chore: abstract `TwoWayMap` to be able to be used for more usecases

### LINKED ISSUE #1414: Abstract `TwoWayMap` to be able to be used for more usecases
### Problem

`TwoWayMap` in the SSA refactoring only maps between a value of type `T` and its corresponding `Id<T>`. This is too narrow to apply to other similar use cases in ACIR-gen or the SSA optimization passes.

### Happy Case

We should change the inner maps of a TwoWayMap from `HashMap<T, Id<T>` and `HashMap<Id<T>, T>` to `HashMap<K, V>` and `HashMap<V, K>`. Then we could use this abstraction for more SSA passes and in ACIR-gen.

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by f01dab1e**
# Description

abstract `TwoWayMap` to be able to be used for more usecases

# Problem

TwoWayMap in the SSA refactoring only maps between a value of type T and its corresponding Id<T>. This is too narrow to apply to other similar use cases in ACIR-gen or the SSA optimization passes.

maybe probably can use it here:
https://github.com/noir-lang/noir/blob/f078188b0ecf8c549ca7bef401c5f137730f6063/crates/fm/src/lib.rs#L34-L35

Resolves #1414 

## Summary

# PR Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by f01dab1e** [comment]
@jfecher, it seems that we are currently not using `TwoWayMap` in any way

**Comment by jfecher** [comment]
@f01dab1e right. We used to use it for constants before it was deemed unnecessary. Once that was removed it was too narrow a use-case to use anywhere else so we want to expand it a bit. One example of a usecase I'd like it to work for would be to replace the `data` and `data_reverse_map` fields in `AcirContext`

**Comment by jfecher** [comment]
The example you linked in `fm` is good too. If we use it there though, we should probably move TwoWayMap to a different crate.

As for the PR itself, it looks good. My only additional request would be to put it in use in e.g. the AcirContext as mentioned. We can avoid the `fm` usecase for now since it would require this be in a new crate since the existing ones wouldn't be applicable.

**Review by jfecher — APPROVED** [review]
👍

**Comment by jfecher** [comment]
The API looks good, although it looks like you have tests failing now

**Review by jfecher — APPROVED** [review]

**Pull request merged**
