### PR TITLE
chore: resolve `Instruction` inputs fully before checking against cache

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves 

## Summary\*

It struck me that we should be fully resolving any inputs to the instruction before we check against the cache. This allows us to catch the maximum amount of duplicate instructions.

What's concerning is that I'm now getting a failed constraint error in the `sha2` tests. This seems otherwise a fairly low-risk change so I'm not sure if there's a deeper issue in #2450 which wasn't caught which means we should revert that change. @jfecher what do you think?

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
> I'm not sure if there's a deeper issue in https://github.com/noir-lang/noir/issues/2450 which wasn't caught which means we should revert that change. @jfecher what do you think?

@vezenovm and I did find a few bugs yesterday in that the DIE pass' definition of a side-effectful instruction was different than the definition needed by this pass to remove duplicates. `allocate` instructions within the same block were getting removed for example. A PR has been merged to fix that, although we found out later that `load` instructions to the same address were getting removed as well - you could try adding that case to see if it fixes your test. I have it locally as well in my mem2reg PRs.

**Comment by vezenovm** [comment]
> It seems like `Truncate` is the culprit here but I can't understand why that would be the case as it's a relatively well-behaved instruction.

This PR maps the instruction inputs values, so perhaps there are two truncates on the same value where one instruction truncates to a smaller bit size. The smaller truncation comes second in line, so the value is replaced with values that have too large of a bit size.

**Comment by TomAFrench** [comment]
The target bitsize is part of the key on the cache though so I would expect that situation not to cause troubles. In any case, now we know it's truncation instructions I'll have a closer look at how these are being optimized out.

**Comment by TomAFrench** [comment]
I'm happy to merge this without `Truncate` and then revisit this later.

**Comment by TomAFrench** [comment]
I'd like to put this into a non-breaking release today before we start merging in the changes from `acvm-backend-barretenberg`.

**Review by jfecher — APPROVED** [review]
`is_pure` is a good addition

**Pull request merged**
