### PR TITLE
chore: brillig IR printer (WIP, kw/x86 base)

### PR DESCRIPTION
**Pull request by ludamad**
# Description

Print brillig IR with labels. WIP

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by ludamad** [comment]
@kevaundray how do you feel about something like this getting in? Feels right to me - we usually want to trace at a higher level than raw brillig, and it could later be expanded to even print hints about the source code things come from etc

**Comment by kevaundray** [comment]
> @kevaundray how do you feel about something like this getting in? Feels right to me - we usually want to trace at a higher level than raw brillig, and it could later be expanded to even print hints about the source code things come from etc

Yep this make sense -- I reverted initially because the call instruction PR had nothing to do with printing, ie we'd want this change to go straight into master -- it will be faster to merge than the call instructions PR.

I'm not sure about having `debug_show` being put in functions vs having a method which operates over the BrilligArtifact and prints it. The latter means there is only one place I need to worry about when I need to configure printing the IR. What you lose is granularity, ie in the former you can print an opcode and then print something related to the function in that same function and they will be interleaved. If you want to add hints or other information, I can see the former adding noise to functions depending on how much information you want to add. In the latter approach, you would need to store this information in the BrilligArtifact as a Map and then when you are printing the Brillig IR, you access the maps to pretty-print more information.

The reason why I'm not firmly in the "print the IR at once" boat, is because these methods are only in brillig_ir right now and if I were to add a new method which pushed a new instruction I think it would be easy to figure out that it would need a debug_show at the top. 

What are your thoughts?

**Comment by ludamad** [comment]
I guess one thing is that it would not be hard right now to make a debug print statement in the brillig SSA layer and get more info, whereas otherwise it would be a harder thing to trace. I'm open, I like this pound for pound though I think because this is scrappy enough to maintain easily and also general because you can emit prints in-between from the SSA layer, something harder to do one-shot

**Comment by ludamad** [comment]
Also my reasoning for why the call branch is that this is when things start to get complicated - but open to backport, I guess slices wants it too. I also thought calls was close with Alvaro's recent fixing of arrays + wanted to peek at it

**Comment by ludamad** [comment]
But I suppose the same goes for dynamic slices. TBH if I worked on both I'd just copy this as it's very easy little glue code

**Comment by ludamad** [comment]
Downside of this approach is the scrappiness does show - STOP gets printed as RETURN before being patched, if you want to print something higher level and not print in the lower level utility functions its tricky, etc

**Comment by kevaundray** [comment]
> Also my reasoning for why the call branch is that this is when things start to get complicated - but open to backport, I guess slices wants it too. I also thought calls was close with Alvaro's recent fixing of arrays + wanted to peek at it

I'd prefer to merge into master so that branches are as self contained for a feature as possible. It makes writing code harder, but it makes reviewing code easier imo which is what I like to optimize for!

**Pull request closed without merging**
