### PR TITLE
feat: add `as_witness` builtin function in order to constrain a witness to be equal to a variable 

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Quick fix to #4629 

## Summary\*

This PR adds a `as_witness` function which takes a `Field` and instructs the compiler to lay down an opcode which constrains a witness to be equal to this value.

This prevents the issue in #4629 where we collect ever growing expressions which need to be broken down multiple times while reshaping the circuit. Doing this during acirgen instead allows us to avoid this repetition.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [x] **[For Experimental Features]** Documentation to be submitted in a separate PR.
Feature is experimental

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
I've confirmed that this works on @zac-williamson's poseidon circuit. Happy to bikeshed on naming.

**Comment by jfecher** [comment]
I'd like to hold off on this unless @zac-williamson really needs a fix today for this. I just don't see regular users being able to debug to the point where they can identify the exact point to add `as_witness` if it is needed.

**Comment by TomAFrench** [comment]
Happy to hold off on this if it's not urgent, just good to have this in our back pocket.

**Comment by TomAFrench** [comment]
@jfecher can you approve?

**Review by jfecher — APPROVED** [review]

**Pull request merged**
