### PR TITLE
chore(ci): use `actions/setup-node` for caching yarn dependencies

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves 

## Summary\*

This PR addresses https://github.com/noir-lang/noir/pull/2697#discussion_r1327635425

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by kevaundray — APPROVED** [review]
I guess once we use this setup file for more than typescript, this would be put back to actions/cache since thats more general question mark question mark

**Comment by TomAFrench** [comment]
This adds ~20s onto any JS job but we get the benefits of more modern nodejs + extra safety guarantees that the cache contents is correct.

**Comment by TomAFrench** [comment]
@kevaundray Requesting another review as the last one was multiple months ago.

**Review by kevaundray — APPROVED** [review]

**Comment by TomAFrench** [comment]
> I guess once we use this setup file for more than typescript, this would be put back to actions/cache since thats more general question mark question mark

For completeness, if we had stuff other than yarn dependencies to cache then we'd place them in a different cache with a potentially different cache key.

**Pull request merged**
