### PR TITLE
chore(nargo)!: rename `contract` command to `codegen-verifier`

### LINKED ISSUE #945: Rename `nargo contract` command
As we add Noir contracts, there's going to become confusion around the `nargo contract` command. Does it create a solidity verifier contract or does it do something else related to noir contracts?

We should then update the name to avoid any confusion. One option is:

> `nargo generate-verifier --solidity` perhaps? We could then extend it to other languages, etc.

_Originally posted by @TomAFrench in https://github.com/noir-lang/noir/issues/944#issuecomment-1454160836_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Related issue(s)

Resolves #945 

# Description

## Summary of changes

I've renamed the `nargo contract` command to `nargo codegen-verifier`. `codegen` is shorter than `generate` and is more descriptive so I opted for this name instead of what's discussed in #945 (happy to switch if there's strong feelings about this).

## Test additions / changes

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

## Documentation needs
- [x] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

**Comment by kevaundray** [comment]
Did you consider 'gen-verifier' ?

**Comment by TomAFrench** [comment]
Yeah, I did. It felt a little _too_ abbreviated in my mind. "codegen" is a well-known term but "gen" has no meaning until the user makes the leap to "generate"

**Comment by kevaundray** [comment]
Fair, I have no strong opinion re this. Quick ping to @noir-lang/tooling

**Comment by kevaundray** [comment]
I pinged @joss-aztec since he replied to the original issue and he says your new suggestion is even better

**Review by kevaundray — APPROVED** [review]

**Pull request merged**
