### PR TITLE
feat: Sync from aztec-packages

### PR DESCRIPTION
**Pull request by AztecBot**
Automated pull of Noir development from [aztec-packages](https://github.com/AztecProtocol/aztec-packages).
BEGIN_COMMIT_OVERRIDE
chore(avm-simulator): update e2e test (https://github.com/AztecProtocol/aztec-packages/pull/5283)
feat!: Acir call opcode (https://github.com/AztecProtocol/aztec-packages/pull/4773)
feat: initial Earthly CI (https://github.com/AztecProtocol/aztec-packages/pull/5069)
feat: Check initializer msg.sender matches deployer from address preimage (https://github.com/AztecProtocol/aztec-packages/pull/5222)
feat: Sync from noir (https://github.com/AztecProtocol/aztec-packages/pull/5234)
feat: Brillig IR refactor (https://github.com/AztecProtocol/aztec-packages/pull/5233)
feat(avm): brillig CONST of size > u128 (https://github.com/AztecProtocol/aztec-packages/pull/5217)
feat: New brillig field operations and refactor of binary operations (https://github.com/AztecProtocol/aztec-packages/pull/5208)
feat!: Support contracts with no constructor (https://github.com/AztecProtocol/aztec-packages/pull/5175)
END_COMMIT_OVERRIDE

### CODE REVIEW

**Review by sirasistant — APPROVED** [review]

**Comment by TomAFrench** [comment]
This is going to need a new bb version in order to pass tests afaik. Were these changes included in the release today?

**Comment by sirasistant** [comment]
Ah true, forgot about the serialization change. I don't think it's released yet!

**Comment by sirasistant** [comment]
Oh, it went in in 0.28. Will try updating, let's see https://github.com/AztecProtocol/aztec-packages/pull/5192

**Comment by sirasistant** [comment]
Closing to try to fix sync

**Pull request closed without merging**
