### PR TITLE
chore!: Require package names in `Nargo.toml` files

### LINKED ISSUE #2053: Require crate name in nargo.toml
### Problem

With the addition of workspaces into Nargo, we need to start requiring package names for crates. This allows users to run commands in a specific crate using the `--package` flag.

### Happy Case

All packages will have a name so all commands can eventually have a `--package` flag

### Alternatives Considered

_No response_

### Additional Context

I noticed that some tests have invalid names, so we need to move that to an optional `description` field, which we can do at the same time.

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by phated**
# Description

## Problem\*

Resolves #2053 

## Summary\*

This makes the `name` field in Nargo.toml required. By making this required, we can add a `--package` flag to any command to select a package in a workspace. While updating the tests, I found that some `name` fields in Nargo.toml were invalid package names, so I moved the name to a `description` field (which we now parse) and added a proper name.

This is breaking because previous projects will have been generated without a name, but new projects generated by nargo will set the directory name as the package name.

This work fell out of #1992 but should be merged as a prerequisite.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
This is going to break all of the existing `Nargo.toml` files in the wild. Users are going to see the below error message.

```
Error: Nargo.toml is badly formed, could not parse.

 data did not match any variant of untagged enum Manifest


Caused by:
    data did not match any variant of untagged enum Manifest


Location:
    crates/nargo_cli/src/cli/mod.rs:74:5
```

This doesn't really give much information on how to fix the issue. Can we display a message showing that the user should add a `name` field?

**Review by kobyhallx — DISMISSED** [review]
👍

**Comment by TomAFrench** [comment]
@kobyhallx Are you sure we want to merge like this? We're going to get a ton of issues in the Discord as a result.

**Comment by kobyhallx** [comment]
@TomAFrench this is marked breaking change and would affect the next release. What's the alternative to introduce this change?

**Review by TomAFrench — CHANGES_REQUESTED** [review]
Will demonstrate in a few mins

**Review by TomAFrench — APPROVED** [review]
@kobyhallx We now display in the panic message what the user needs to do in order to make their toml file valid again.

**Comment by TomAFrench** [comment]
Gonna let @phated pull the trigger on this one as he's gonna be up soon.

**Comment by Savio-Sou** [comment]
Any doc needs for the PR?

**Comment by phated** [comment]
@Savio-Sou I scanned the noir-lang.org website and couldn't find any mention of the contents of nargo.toml, so I didn't mark it as needing documentation.

**Comment by Savio-Sou** [comment]
Good point, we should probably document Nargo.toml in that case. Thanks!

**Pull request merged**
