### PR TITLE
feat: Visible aliases for nargo commands

### LINKED ISSUE #4452: Add visible aliases for main Nargo commands
### Problem

Currently, Nargo lacks aliases that developers could use to streamline the execution of their most frequently used commands.

### Happy Case

e.g. `nargo c` for `nargo check`

### Project Impact

Nice-to-have

### Impact Context

Improves dev experience

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

No

### PR DESCRIPTION
**Pull request by nicolasgarcia214**
# Description

Closes #4452

## Documentation\

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by jfecher — COMMENTED** [review]
Thanks for the PR! Do you mind adding an alias for `nargo execute` as well?

**Comment by nicolasgarcia214** [comment]
Hi @jfecher,

Sure, I pushed the new alias for the execute command as discussed, but it's not showing up in the PR yet. Here's the commit: [b7f1d6c](https://github.com/nicolasgarcia214/noir/commit/b7f1d6c05c56f779ff6ed17e889cf464414c2ef6)

**Comment by nicolasgarcia214** [comment]
Currently there is an incident with [Pull Requests and Actions](https://www.githubstatus.com/incidents/wcl1sw4mzg60). 
> Sporadic delays in pull request synchronization and reduced Actions throughput.

**Review by jfecher — APPROVED** [review]
Thank you :+1:

**Pull request merged**
