### PR TITLE
chore(ci): Active rollup circuits in compilation report

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Started as investigations into https://github.com/noir-lang/noir/pull/6750#discussion_r1878881848, but looks like the memory issues have been resolved by recent updates. Specifically this switch to `u32` for Id https://github.com/noir-lang/noir/pull/6807.

## Summary\*

Simply activates the two commented out rollup circuits. 

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
We don't have a workspace `Nargo.toml` by default in aztec-packages. This needs to be generated by the `generate_variants.js` script.

**Comment by TomAFrench** [comment]
See https://github.com/AztecProtocol/aztec-packages/tree/master/noir-projects/noir-protocol-circuits

**Comment by vezenovm** [comment]
> We don't have a workspace `Nargo.toml` by default in aztec-packages. This needs to be generated by the `generate_variants.js` script.

Ah yes I forgot about this

**Comment by TomAFrench** [comment]
I think that using the action may conflict with our cache of node modules

**Comment by vezenovm** [comment]
I'm going to keep this open but just for investigating https://github.com/noir-lang/noir/pull/6750#discussion_r1878881848

**Comment by vezenovm** [comment]
> rollup-base-public	6m5.361s
> rollup-base-private	3m42.685s

Huh, these did not time out as expected

**Comment by vezenovm** [comment]
Those circuits must have been using too much memory previously and been messing with the runner. Memory should be largely improved after changes like this one https://github.com/noir-lang/noir/pull/6807, thus we can run these reports again.

**Review by TomAFrench — APPROVED** [review]

**Comment by TomAFrench** [comment]
Do the rollup circuits still compile when using heaptrack? If so we should add them to the memory tracking Ci as well.

**Comment by vezenovm** [comment]
> Do the rollup circuits still compile when using heaptrack? If so we should add them to the memory tracking Ci as well.

I did not try on the CI as the noir-contracts still do not compile when using heaptrack in the CI and they take ~2m40s vs. 3m and 5m for the rollup circuits. Generally it looks like heaptrack takes 10x as long as normal execution.

I did compile the rollup-base-private locally with heaptrack and got 24G.

**Pull request merged**
