### PR TITLE
fix: fix scalar mul in stdlib/ec

### LINKED ISSUE #5259: scalar multiplication should account for zeros from MSB end
https://github.com/noir-lang/noir/blob/d9b4712bf1a62548dd7ed17b181882ae537d70dd/noir_stdlib/src/ec/swcurve.nr#L339
https://github.com/noir-lang/noir/blob/d9b4712bf1a62548dd7ed17b181882ae537d70dd/noir_stdlib/src/ec/swcurve.nr#L352
Currently it will double the point `N` times even when multiplying by $1$.

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #5259 

## Summary\*
refactor the square and multiply

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
We have this same code repeated in the other `ec` submodules so we should make those changes there as well.

**Comment by guipublic** [comment]
I fixed the code also in tecurve.rs, I did not find another instance.

**Comment by TomAFrench** [comment]
I think we can leave this until Zac's improved implemention is ready. This also causes a performance degradation it seems.

**Comment by Savio-Sou** [comment]
> Zac's improved implemention

Is that on a branch / PR?

**Comment by TomAFrench** [comment]
That's in his separate repository that he's been posting in slack.

**Comment by Savio-Sou** [comment]
Oh https://github.com/zac-williamson/noir_bigcurve? Thanks

**Pull request closed without merging**
