### PR TITLE
chore(stdlib)!: Change stdlib methods to accept slices

### LINKED ISSUE #1842: Compiler error hashing a field
### Aim

I'm new to Noir and trying to learn more about how it works.  My first example was just to attempt to hash a Field.  `nargo check` succeeds just fine, but if I attempt to actually run the test or prove, I get the below compiler error.

### Expected Behavior

The test would run and field would be hashed (or show me the error of my ways)

### Bug

```bash
$ nargo test
Running 1 test functions...
Testing test_main...
The application panicked (crashed).
Message:  invalid input
Location: crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs:184

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### To Reproduce

Try to run `nargo test` on the following circuit:

```rust
use dep::std::hash;

fn main(thing : Field) {
    let chash = hash::keccak256(thing.to_le_bytes(8));
    assert(chash[0] > 0 | chash[1] > 0);
}

#[test]
fn test_main() {
    let thing = 123;
    main(thing);
}

```

### Installation Method

Binary

### Nargo Version

nargo 0.6.0 (git version hash: 0181813203a9e3e46c6d8c3169ad5d25971d4282, is dirty: false)

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #1842

## Summary\*

Move from generic arrays syntax on methods to slices in the SSA

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
Yeah Jake's probably the best to review this sensibly.

**Comment by vezenovm** [comment]
Changing the Poseidon generics was leading to some issues during branch analysis. For now this PR just updates the hash functions to accept slices

**Comment by jfecher** [comment]
I'm not sure about this change. It seems to be putting a band-aid over the real problem of `to_le_bytes` and friends lying about their type signature. This may fix the linked bug but there are also several other bugs that are a result of the same issue in `to_le_bytes`.

 I think to properly fix it we need to fix `to_le_bytes` to return an array of some maximum length, with any extra space filled up with zeroes. If we want to be wary of the Field size changing we can add an assert that the field size is smaller than whatever can fit in the maximum length we decide upon. We should just document that it will fail if the field size and value are too large.

**Comment by vezenovm** [comment]
Closing in favor of #2070

**Pull request closed without merging**
