### PR TITLE
chore: Expand end to end test suite

### PR DESCRIPTION
**Pull request by f01dab1e**
# Description

expanded test suite

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by f01dab1e** [comment]
@kevaundray hi, is there any feedback for the pull request?

**Review by kevaundray — APPROVED** [review]
More test vectors are good, most of these will be testing the parser and const eval

**Review by kevaundray — APPROVED** [review]

**Review by TomAFrench — CHANGES_REQUESTED** [review]
These need to have artifacts generated for barretenberg to test against. The `workspace` test is also breaking barretenberg tests.

**Comment by kevaundray** [comment]
> These need to have artifacts generated for barretenberg to test against. The `workspace` test is also breaking barretenberg tests.

I'll open an issue to discuss how to generate these automatically, since manually doing this is not a great process

**Review by jfecher — CHANGES_REQUESTED** [review]
I think these tests intersect too much with existing tests rather than testing previously untested features. We already have tests for `if` and generics for example.

**Comment by f01dab1e** [comment]
@jfecher, what is better to cover with tests?"

**Comment by jfecher** [comment]
@f01dab1e I think we're good at the moment for these integration tests. If you ever find a new bug that wasn't caught by previous tests then feel free to add one.

**Pull request closed without merging**
