### PR TITLE
chore: switch to Noir Keccak implementation with variable size support

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

We are still using a blackbox function for Keccak, while we have the keccak permutation blackbox.

## Summary\*

Add variable size support for Noir Keccak, and also switch to the Noir implementation in stdlib

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by guipublic** [comment]
I investigated the circuit size increase in the report as it does not match my own tests. It was because the test is using constant input which was simplified. I have added constant folding also for keccak permutation. This resolves the issue.

**Comment by TomAFrench** [comment]
Nice, looking much better now. Can you chuck a `no_predicates` on the hash function?

**Comment by guipublic** [comment]
> Nice, looking much better now. Can you chuck a `no_predicates` on the hash function?

on which one? keccak256 already has one so I am not sure which one you refer to?

**Comment by TomAFrench** [comment]
Ah yeah, sorry I missed that.

**Review by TomAFrench — APPROVED** [review]

**Pull request merged**
