### PR TITLE
Change Backend Default to WASM

### PR DESCRIPTION
**Pull request by Globallager**
Change the default backend to `wasm-base` with the intention of saving first-time Noir developers from struggling with compiling the C++ backend.
Feel free to modify / reject.

(Apologies for Prettier's auto-formatting.)

### CODE REVIEW

**Comment by TomAFrench** [comment]
This would break any usage of `nargo contract` in the meantime as `wasm-base` doesn't have an implementation of [`eth_contract_from_cs`](https://github.com/noir-lang/aztec_backend/blob/26bea43311bc93cf515083825faa834bbe583f11/src/acvm_interop/smart_contract.rs#L21). Is that expected?

**Comment by Globallager** [comment]
On the contrary I couldn't get `nargo` installed on my local machines at all, at least not until I successfully debug the C++ compilation errors I got.
Is there a way where we can close the gap and achieve both?

**Comment by TomAFrench** [comment]
I was having some real troubles with both methods tbh. I ran into a bunch of issues with dependencies which weren't specified in the docs (`cmake`, `clang`, `libomp-dev` and maybe others) which I didn't have as I was installing on my laptop. Even then I was getting rust always panicking until I managed to rebuild `nargo` the magic number of times to make it start working.

**Comment by Globallager** [comment]
To discuss further and re-open with another branch if appropriate.

**Pull request closed without merging**
