### PR TITLE
fix: Update using-devcontainers.mdx

### LINKED ISSUE #4680: chore(doc): One step is missing
Problem：After step 6, go directly to step 8, seems missing the discription of step 7- the building process.

location: How to guides/Developer Containers and Codespaces

### PR DESCRIPTION
**Pull request by ziyinlox-purple**
# Description

## Problem\*

Resolves #4680

## Summary\*
Supplementing the missing creation step 7

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by signorecello** [comment]
Hey @ziyinlox-purple thanks for your contrib and bugfix. Can I ask if you could put these commands inside the Dockerfile itself or in the "onCreateCommand" property of `devcontainer.json`?

Totally fine if you don't feel like it, just let me know and I can do it. We could then merge this one :)

**Review by signorecello — CHANGES_REQUESTED** [review]
Asking stuff

**Comment by ziyinlox-purple** [comment]
> Hey @ziyinlox-purple thanks for your contrib and bugfix. Can I ask if you could put these commands inside the Dockerfile itself or in the "onCreateCommand" property of `devcontainer.json`?
> 
> Totally fine if you don't feel like it, just let me know and I can do it. We could then merge this one :)

ok，I will put it into the `devcontainer.json`

**Comment by ziyinlox-purple** [comment]
> Hey @ziyinlox-purple thanks for your contrib and bugfix. Can I ask if you could put these commands inside the Dockerfile itself or in the "onCreateCommand" property of `devcontainer.json`?
> 
> Totally fine if you don't feel like it, just let me know and I can do it. We could then merge this one :)

Have done, check it please.

**Review by critesjosh — COMMENTED** [review]
Is this only relevant for v0.26? You are only updating this version.

**Comment by ziyinlox-purple** [comment]
No, this is not limited to version v0.26. A step was missing in the
original documentation, which may have confused developers who haven't used
devcontainer before, or they may need to refer back to the video for
guidance. The modified code can now assist them directly in reducing steps
during Codespace creation without affecting the security of subsequent
operations. I'm happy to provide any further explanations or modifications
if needed.🫡

josh crites ***@***.***> 于2024年4月25日周四 03:25写道：

**Comment by ziyinlox-purple** [comment]
Already Updated! 🌞

Cat McGee ***@***.***> 于2024年4月30日周二 22:39写道：

**Comment by TomAFrench** [comment]
@signorecello what's the status of this PR?

**Pull request closed without merging**
