### PR TITLE
chore: add check links

### PR DESCRIPTION
**Pull request by f01dab1e**
# Description

chore: add check links

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by f01dab1e** [comment]
@signorecello, to fix this error, how can it be done?
image

**Comment by signorecello** [comment]
let me try to reproduce... damn docs workflow...

**Comment by signorecello** [comment]
can't reproduce, seems like your branch is out of date... I'm also wondering why are you using `untitaker/hyperlink`, it checks for broken links but that's already done by `docusaurus build`...

**Comment by f01dab1e** [comment]
We had non-working links; I didn't know that there's already a check in Docusaurus build. Probably because the workflow is triggered only if the documentation is being edited, we sometimes miss such moments.

**Comment by f01dab1e** [comment]
#3498 but now falls for another reason

**Pull request closed without merging**
