### PR TITLE
chore: Fix cspell issues for `booleanity` and `nand`

### PR DESCRIPTION
**Pull request by kevaundray**
# Description

This PR adds the words booleanity and NAND to the dictionary. Before merging, we should check that these words need to be added, ie whether we can modify the sentences to not need them.

## Problem\*

Resolves 

## Summary\*

This PR sets out to

### Example

Before:

```

```

After:

```

```

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
`y_booleanity_constraint` -> `y_is_boolean_constraint`

**Review by TomAFrench — DISMISSED** [review]
LGTM. I've done some minor formatting changes in the doc comment for `is_equal` as well ~~plus removed the lines~~

```
    /// Note: We eventually need to apply constraints that ensure that it is a boolean.
    /// But right now with no constraints applied to it, it is essentially a free variable.
```

~~As this appears to be stale as we create a constraint on L322~~

**Review by TomAFrench — APPROVED** [review]
Restored removed comment and reworded it to make it clearer that it's the current behaviour of the code rather than something to be added in future.

**Comment by kevaundray** [comment]
LGTM gracias

**Pull request merged**
