### PR TITLE
feat: bubble up `Instruction::Constrain`s to be applied as early as possible.

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves 

## Summary\*

This PR adds a very simple pass which moves any `Instruction::Constrain`s to immediately after when all of their inputs are available. This allows the ACIR gen pass to use this information earlier as well as simplifying using these constraints in order to inform constant folding in future.

## Additional Context

Pulled out from #4060 

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by vezenovm** [comment]
Does this bug still occur with this change? https://github.com/noir-lang/noir/issues/2645

**Comment by TomAFrench** [comment]
> Does this bug still occur with this change? #2645

It shouldn't, no. This is because the `side_effects_enabled_var` is used to calculate the values being constrained as shown [here](https://github.com/noir-lang/noir/blob/418ffa6b4940102348ede029cc6c7092878c92e9/compiler/noirc_evaluator/src/ssa/opt/flatten_cfg.rs#L642-L665). This means that the constraint can't bubble up higher than the relevant `Instruction::EnableSideEffects` instruction.

**Review by jfecher — APPROVED** [review]
The code looks good, but can you elaborate more on why we're seeing constraint count reductions in this PR, before the change in constant folding has been made?

**Comment by TomAFrench** [comment]
> can you elaborate more on why we're seeing constraint count reductions in this PR, before the change in constant folding has been made?

Because as well as SSA, ACIR generation can benefit from this change as it will replace the `AcirVar` which got constrained with a simpler/constant value. We then optimise out a number of constraints due to ACIR discovering that they are satisfied at compile time.

**Pull request merged**
