### PR TITLE
chore: switch integration tests to mirror CLI usage

### PR DESCRIPTION
**Pull request by TomAFrench**
# Related issue(s)

Resolves https://github.com/noir-lang/noir/pull/1177#issuecomment-1514756689

# Description

## Summary of changes

This PR changes the integration tests to work using the CLI directly to ensure exact parity between this and real-world usage. i.e. rather than using `prove_and_verify` we actually use `nargo prove` and `nargo verify`.

As part of this I've done some general refactoring as this code is unnecessarily complex (3 layers of nesting to just iterate through test cases).

## Test additions / changes

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

## Documentation needs
- [ ] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

**Comment by TomAFrench** [comment]
@kevaundray This adds another ~10mins to the ubuntu run (up from 18mins)

**Comment by TomAFrench** [comment]
I've separated all the readability improvements into #1180 so we can merge those even in the case we don't go ahead with this change. (plus it will highlight the substantive changes here more clearly)

**Comment by kevaundray** [comment]
> 

Ah thats horrible

**Comment by jfecher** [comment]
What is the reasoning for the extra 10 minutes of runtime?
Honestly that seems like a large enough downgrade that I'm wary of merging this at all

**Comment by TomAFrench** [comment]
Comparing [this PR](https://github.com/noir-lang/noir/actions/runs/5515582388/jobs/10056047155) with [master](https://github.com/noir-lang/noir/actions/runs/5515529318/jobs/10055943765).

There's a 5 second difference between the two now that we're not proving and verifying.

**Review by jfecher — APPROVED** [review]
👍

**Pull request merged**
