### PR TITLE
Add `--allow-warnings` flag to treat certain errors as warnings

### PR DESCRIPTION
**Pull request by jfecher**
# Related issue(s)

Relates to "Change unused variables to warnings" #263.

# Description

This PR has the same effect as #263 but puts this behavior behind a compile flag `--allow-warnings`. The "allow-warnings" flag was chosen instead of a more specific flag relating to unused variables because of the implementation in the Diagnostics reporter which simply changes all Warnings to errors if the flag is not set.

Thanks to @vezenovm for adding the flag to #263. This is created as a new PR on a new branch since I opted to start over and cherry-pick + manually apply changes instead of fixing 12k+ lines of conflicts with master.

## Test additions / changes

(If applicable.)

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

# Additional Information

This PR is only a draft right now due to a bug with the verify command not finding the `allow-warnings` flag. The `args.is_present("allow-warnings")` returns false for some reason.

### CODE REVIEW

**Comment by guipublic** [comment]
Just to be sure I understand properly;  this PR makes the unused variable error as a warning, but by default warnings are treated like an error. Then there is the allow-warning flag to be able to compile with warning?

**Comment by jfecher** [comment]
That is correct - this PR is also the same as @vezenovm's with just the flag name changed and merge conflicts with master fixed

**Comment by jfecher** [comment]
I'd also be open to changing the flag name if you have a clearer suggestion

**Comment by guipublic** [comment]
> I'd also be open to changing the flag name if you have a clearer suggestion

allow-warnings for allowing warnings seems like a good name to me!

**Comment by vezenovm** [comment]
I kind of like the flag `--dev` as it is faster to type, but I am good with `--allow-warnings` as well. I don't think `--dev` would be unclear though as it follows the "development" modes that you see in other languages/frameworks where many more errors are emitted.

**Review by guipublic — APPROVED** [review]
Good to have this, finally!

**Review by vezenovm — APPROVED** [review]

**Review by guipublic — APPROVED** [review]

**Pull request merged**
