### PR TITLE
feat: Support `contract` package type for the `info` command

### PR DESCRIPTION
**Pull request by Ethan-000**
# Description

## Problem\*

Resolves https://github.com/noir-lang/noir/issues/1970

## Summary\*

```rust
fn main(x : Field, y : pub Field) {
    assert(x * 2 == y * 3);
}

contract Foo {
    fn double(x: Field) -> pub Field { x * 2 }
    fn triple(x: Field) -> pub Field { x * 3 }
    internal fn quadruple(x: Field) -> pub Field { x * 4 }
    open internal fn skibbidy(x: Field) -> pub Field { x * 5 }
}
```

run `nargo info --contracts` in the `contracts` test in `test_data` now returns 

run `nargo info --contract Foo` returns

run `nargo info --contract F` returns

## Documentation

- [x] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

This does not look very good imho so this issue is opened to address this and others https://github.com/noir-lang/noir/issues/2089

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by iAmMichaelConnor** [comment]
Thanks so much for this!

If I may, it'd be even sexier if the data could be tabulated, e.g. using the `prettytable` crate (or something).

A more advanced question: for an ultraplonk backend, tables are used in some computations (e.g. hashing). Now the 'circuit size' has three interesting pieces of information:
- the number of gates/constraints (as is shown in your lovely examples above)
- the total number of 'rows' in all plookup tables
- the next largest power of two, which is greater than `max(# gates, # table rows)`.

As an extreme example, a circuit might only have 10 gates, but could include a table which is 10,000 rows. Then the proving time will be greatly affected by these 10,000 rows. The important metric for proving time is then: 2^14 = 16,384.
I.e. `2.pow(ceiling(log_2(max(# gates, # rows)))`

**Comment by iAmMichaelConnor** [comment]
Whoops, you beat me to it, re formatting :) https://github.com/noir-lang/noir/issues/2089

**Comment by iAmMichaelConnor** [comment]
@codygunton might be able to point you to the relevant functions. That one looks like it might be correct, for giving you the value `max(# gates, # table rows)`.

As for whether the Noir backend uses this (and is 'allowed' to make a call to get this information, without sacrificing 'backend agnosticism'), someone on the Noir team will need to help you there :)

**Comment by vezenovm** [comment]
> As for whether the Noir backend uses this (and is 'allowed' to make a call to get this information, without sacrificing 'backend agnosticism'), someone on the Noir team will need to help you there :)

This is the UP backend method that is called by `nargo info`.

**Comment by iAmMichaelConnor** [comment]
I'd be in favour of providing all the numbers. As much useful info as we can be given :)

**Comment by kevaundray** [comment]
@phated whats the status #2075 ? If it is not completed, then I'd opt for reviewing and merging this in and when that PR lands, it rebases off of this

**Comment by phated** [comment]
> whats the status https://github.com/noir-lang/noir/issues/2075 ? If it is not completed, then I'd opt for reviewing and merging this in and when that PR lands, it rebases off of this

I'm trying to answer some design questions right now, but hoping to have something up by end of tomorrow. We could merge this, but then there'd be a "breaking" change that only affects people that built a compiler between this PR and my PR (since mine will be removing both flags) and it seems like unnecessary/confusing churn.

**Comment by phated** [comment]
I created #2204 to unblock this without churn.

**Comment by TomAFrench** [comment]
We should also add support for contracts in `nargo check`. We can't produce a `Prover.toml` file but we can check that the Noir is syntactically correct.

**Comment by kevaundray** [comment]
@Ethan-000 #2204 is getting merged, can you rebase and mark as ready when you are ready for a review

**Comment by phated** [comment]
Updated the title to reflect the implementation that needs to happen 🙇

**Pull request closed without merging**
