### PR TITLE
fix: Print `comptime::Value` better

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Summary\*

Several Value variants are just ids which we previously couldn't print well. I've added a helper type to hold a NodeInterner so that we can print the names of these values as well. This will now print, e.g. `Eq` instead of `(trait definition)`

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by asterite — APPROVED** [review]
LGTM

Is there a way to test this? (maybe it's tricky because this would be the output of a `println` call?)

**Comment by jfecher** [comment]
@asterite not that I know of besides testing it manually.

I'm surprised there are circuit size changes here at all though. Especially considering this is just changing the comptime values printing and not runtime ones.

**Comment by asterite** [comment]
Ah, you are right. 

I just checked out the branch this PR is on top of, `jf/quoted-to-trait-constraints`, and I see the bump in size also happens there. I don't know why a message wasn't posted in that PR, though.

**Comment by asterite** [comment]
Nevermind, now I don't get that difference in that other PR... 🤔

**Comment by asterite** [comment]
Oh, and merging this branch against master makes it go down again... I think. We'll have to wait for the other PR to get merged, then merge against master.

**Comment by vezenovm** [comment]
> Oh, and merging this branch against master makes it go down again... I think. We'll have to wait for the other PR to get merged, then merge against master.

Yeah I think so as well. If you look in the `Report gates diff` action you will see `Downloading artifact "jf-quoted-to-trait-constraints.gates_report.json" of repository "noir-lang/noir" with ID "1761974290"` under the `Compare gates report` step.

**Pull request merged**
