### PR TITLE
feat: implement euclidean division and signed division in terms of `AcirVar`s

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves 

## Summary\*

We're being quite inefficient when we're generating ACIR as we're throwing away a lot of information when implementing logic inside `GeneratedAcir` rather than `AcirContext`.

For instance, when checking if the `rhs` of euclidean division is non-zero we always create a new witness even if `rhs` is a constant. Moving this logic up to `AcirContext` allows us to take this information into account and so generate fewer constraints/witnesses.

I've broken this PR down so that each commit tackles migrating a different function so reviewing commit-by-commit is recommended.

The main target of this PR is euclidean division can be implemented but in order to do this then we have to bring up signed division and "more than eq".

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
image

This is a relatively extreme example but this reduces the number of constraints on eddsa by ~7%

**Comment by kevaundray** [comment]
pinging @guipublic for a review

**Review by guipublic — APPROVED** [review]
LGTM
I did not review the logic line-by-line but I assume it is a copy/paste from generater_acir.rs so the logic did not change.

**Comment by TomAFrench** [comment]
Yep, I've kept the logic the same and just updated as necessary to use `AcirVar`s

**Pull request merged**
