### PR TITLE
chore: move nargo I/O into separate module

### LINKED ISSUE #884: Separate off IO from nargo command logic
# Problem

Currently we've got IO logic spread across the entire `cli` directory - some in a `X_cmd.rs` file to be used locally, some in `mod.rs` to be used in several files.

This causes a large amount of noise which makes it harder to find the actual business logic.

# Solution

We can create single module which holds all of the IO logic which the files defining each command can just import as needed.

```
auth
├─ mod.rs
├─ commands
│  ├─ check_cmd.rs
│  ├─ compile_cmd.rs 
│  ├─ etc.
├─ fs
│  ├─ keys.rs
│  ├─ inputs.rs
│  ├─ etc.

```

The major benefit I see for this is that it makes reworking how we perform IO (necessary for the new build artifact format) easier due to the increased encapsulation. 

Other benefits include:
- simplifying the CLI files.
- making it easier to define a specific error type for IO issues.

# Alternatives considered

We can maintain the IO alongside the CLI logic.

# Additional context

### PR DESCRIPTION
**Pull request by TomAFrench**
# Related issue(s)

Resolves #884 

# Description

## Summary of changes

The majority of the changes are just moving functions which load/write to file into the new `fs` module. I've also removed the preprocessing logic from `fetch_pk_and_vk` so that it's pure I/O as it's the CLI's responsibility to perform preprocessing where necessary.

## Test additions / changes

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.
- [ ] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

**Comment by phated** [comment]
Do we want to take this further and split into the `nargo-core` and `nargo-cli` crates like @kevaundray suggested? I could see `nargo-core` becoming the basis for wasm stuff instead of the special `noir_wasm` crate.

**Review by jfecher — APPROVED** [review]
I'm fine with splitting out nargo-cli into a separate crate if it means less code duplication for the wasm crate, but this should be in a separate PR.

**Comment by TomAFrench** [comment]
I'm aiming to not change functionality as much as possible in this PR so that substantive changes can be reviewed separately from code reshuffling.

That said, I also think that we should wait until `nargo` sits in its own repository before we split it up.

**Comment by TomAFrench** [comment]
Will merge after #892

**Pull request merged**
