### PR TITLE
chore: Remove  #[allow(clippy::map_entry)] lint

### PR DESCRIPTION
**Pull request by kevaundray**
# Related issue(s)

# Description

Ideally, we would fix by using `.entry.or_insert_with` however since `self` is borrowed when we call `.entry` and then again when we call `add_instruction`. 

The rust compiler cannot see that this is safe. If we were operating on separate fields in the struct, then it should have no problem deducing this, but since we call a method it falls short. This IIRC is something that the new borrow checker Polonius will be able to solve.

## Test additions / changes

# Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [ ] I have reviewed the changes on GitHub, line by line.
- [ ] I have ensured all changes are covered in the description.
- [ ] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

**Comment by kevaundray** [comment]
> I don't see why we'd want to switch from `contains_key` to `.get(...).is_none()`. I also don't think we should remove the lint entirely just because it is wrong for two functions.

Can you elaborate on the reason to not remove the lint? I'm impartial to this one, though in general we should try not to have lint exceptions in the compiler.

I'm impartial to this one because functionally they are the same, so can see a reason to keep it to signal that we want to eventually refactor the code.

**Comment by jfecher** [comment]
I think I was thinking from the PR title that this PR removed the lint entirely from out list of clippy lints. Not sure why I thought that even after I saw the diff of only 1 file.

**Review by jfecher — APPROVED** [review]
I don't think we should in general update our code just to remove a `#[allow(clippy::...)]` line when the code in question is fine. This case is small enough though that it doesn't really matter either way.

**Comment by kevaundray** [comment]
> I think I was thinking from the PR title that this PR removed the lint entirely from out list of clippy lints. Not sure why I thought that even after I saw the diff of only 1 file.

Ahh yeah this is why I kept probing as I was a bit confused

**Comment by kevaundray** [comment]
> I don't think we should in general update our code just to remove a `#[allow(clippy::...)]` line when the code in question is fine. This case is small enough though that it doesn't really matter either way.

I agree. For some cases clippy can be too conservative, especially when you are in a niche domain.

**Pull request closed without merging**
