### PR TITLE
Add partial evaluator to inline before SSA pass

### LINKED ISSUE #461: Add partial evaluator
# Problem

As noir grows we naturally want to add more and more `comptime` features to it, yet arbitrary features can be difficult to add to the SSA pass and it seems unnecessary to have SSA manage all these extra features which should always be removed at compile-time.

# Solution

If we added a partial-evaluation pass to inline functions/loops before SSA and evaluate comptime expressions then it would make several features easier to add in the future: expanding `comptime` expressions, the mini-evaluator in the name resolver can be removed, and for-loops returning arrays can be implemented.

# Alternatives considered

Alternatively, we can add these features all to SSA and deal with them there. Depending on the feature this may be more difficult to add.

### PR DESCRIPTION
**Pull request by jfecher**
# Related issue(s)

Resolves #461

Related to #374

# Description

## Summary of changes

Adds a new pass to the compiler after monomorphisation to inline all functions, unroll for loops, and evaluate comptime expressions. This means we could technically make SSA a bit smaller by removing these things, but this PR avoids doing this to change less code. There can be a later PR. This makes some features easier to add. As an example, for-loops returning arrays has also been implemented in this PR.

As an example

## Test additions / changes

None yet; I will update with a test for the arrays returned by for loops.

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

### CODE REVIEW

**Review by guipublic — CHANGES_REQUESTED** [review]
Unrolling and inlining have a major impact on performance, and the sooner they are done the bigger the impact will be. As a result, it is not a good idea to do it before SSA. To demonstrate this, I could get a program that generates 110000 gates in less than 2 minutes, plus one minute to generate the proof. With this PR, the process commits suicide on the mainframe after something like 20 minutes.
`[1]    2294337 killed     cargo run --release prove p`

This evaluator could be used for evaluating small expressions computing array lengths in array definitions, although it may be better to support non-fixed array structures, which is a better feature and would make this deprecated.

**Comment by jfecher** [comment]
What is the program you're testing with?
I'm aware of some low hanging fruit optimizations-wise that can be fixed rather easily and can test it versus your input

**Comment by guipublic** [comment]
> What is the program you're testing with? I'm aware of some low hanging fruit optimizations-wise that can be fixed rather easily and can test it versus your input

I don't think we should spend time on this, even if we re-implement the optimisations done in SSA, it is still not the correct place for inlining and unrolling. This will mess with further static analysis, handling of non-const in loop ranges, return statements, recursion and even custom gates/lookup tables.
For the record, the program I tried is this:
```
use dep::std;
fn main(x: Field, y: Field, z: Field) {
        let _a = x+y+z;
       let mut h1 = std::hash::mimc_bn254([x,y]) as u32;
       for i in 0..100 {
        if x as u32 +1000<5 {
          h1 = std::hash::mimc_bn254([x+i,y]) as u32;
        } else 
        {
        h1 = std::hash::mimc_bn254([x+500,y]) as u32;
        }
       };
     
   constrain h1>1;
}
```

**Comment by jfecher** [comment]
After timing this some more, it seems the majority of the extra time comes from `optim::full_cse`:
```
PR #462 + minor optimization

Monomorphisation/frontend done: 244.538666ms
Partial evaluation done: 1.02463475s
ssa codegen main done: 4.378943s
  function::inline_all done: 3.416µs
  block::compute_dom done: 54.25µs
  optim::full_cse done: 30.3027525s
  flatten::unroll_tree done: 1.409702833s
  decision tree.reduce done: 6.011341291s
  inline::inline_tree done: 2.997692041s
  block::merge_path done: 3.163667916s
  optim::cse done: 3.160972666s
  integer::overflow_strategy done: 15.337554666s
ssa opts done, total: 62.383857166s
acir gen done: 3.336528291s
total gates: ~12000

--------------------------------
master

Monomorphisation/frontend done: 252.326583ms
ssa codegen main done: 45.760041ms
  function::inline_all done: 1.633393125s
  block::compute_dom done: 28.666µs
  optim::full_cse done: 638.75µs
  flatten::unroll_tree done: 915.583µs
  decision tree.reduce done: 1.97975ms
  inline::inline_tree done: 2.54637325s
  block::merge_path done: 3.075378958s
  optim::cse done: 850.837125ms
  integer::overflow_strategy done: 4.612838541s
ssa opts done, total: 12.722489791s
acir gen done: 1.36219525s
total gates: 6666
```
Although even SSA passes such as integer::overflow_strategy which should occur after all functions are inlined and loops are unrolled normally still take longer.

I think it can still be worth investigating this further since this PR allows changes to the language - like first class functions - more easily than editing the SSA pass and managing its internal state.

**Comment by jfecher** [comment]
It seems the gate count difference was because the PR was not updated with master. After updating and resolving merge conflicts it actually produces fewer gates than master:

```
jf/partial-evaluator> nargo gates
ACIR gates generated : 6655
Gates successfully counted

Total gates: 11662

By type:
arithmetic: 11631
range: 19
split: 2
truncate: 10

master> nargo gates
ACIR gates generated : 6666
Gates successfully counted

Total gates: 15257

By type:
arithmetic: 15226
range: 19
split: 2
truncate: 10
```

**Comment by jfecher** [comment]
Closing this PR as it is used by the higher-order-functions PR anyway and the later PR is somewhat more efficient.

**Pull request closed without merging**
