### PR TITLE
chore: add mold to github action

### LINKED ISSUE #3538: Investigate adding the `mold` linker
### Problem

The [mold](https://github.com/rui314/mold) linker speeds up linking times, we can investigate adding `mold`.

### Happy Case

.

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by f01dab1e**
# Description

## Problem

Resolves #3538 

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by kevaundray** [comment]
Was there any performance difference in adding mold?

**Comment by f01dab1e** [comment]
I don't see any difference, except for a slight noise, which is probably within the margin of error.

**Comment by TomAFrench** [comment]
What's the status of this PR?

**Comment by f01dab1e** [comment]
It seems I couldn't achieve the expected results, perhaps someone else might succeed.

**Pull request closed without merging**
