### PR TITLE
chore(docs): fix wrong Nargo.toml workspace examples

### LINKED ISSUE #4805: docs: workspace page
### Aim

https://noir-lang.org/docs/noir/modules_packages_crates/workspaces

The workspace Nargo.toml currently reads: 

```
[workspace]
members = ["crates/a", "crates/b"]
default-member = "crates/a"
```

It should instead read:
```
[workspace]
members = ["a", "b"]
default-member = "a"
```

i.e. remove the `crates` word from the paths.

Before making this change, I was getting this error when running `nargo compile` from within crate `a`:

```
Cannot read file /Users/mike/git/my_project/crates/crates/a/Nargo.toml - does it exist?
```

Hoping no one else will have to lose 15 mins of life wondering why the workspace wasn't compiling :) 

```
nargo version = 0.26.0
noirc version = 0.26.0+c46b164ce56e6a8f81255fb17eb6539bd040f336
(git version hash: c46b164ce56e6a8f81255fb17eb6539bd040f336, is dirty: false)
```

### PR DESCRIPTION
**Pull request by SihanoukSolver29**
# Description

## Problem\*

Resolves #4805

## Summary\*

This PR fixes the issue found by @iAmMichaelConnor in #4805, where the example Nargo.toml content for [workspace] has 
 members with wrong paths. 

Since the structure has Nargo.toml inside the `crates` folder, then `members` should direct to folders inside `crates`.
``` file structure
├── crates
│   ├── a
│   │   ├── Nargo.toml
│   │   └── src
│   │       └── main.nr
│   └── b
│       ├── Nargo.toml
│       └── src
│           └── main.nr
├── Nargo.toml
└── Prover.toml
```

## Additional Context

All nargo versions I've tested with, from v0.19.0 to v0.27.0, return `Cannot read file /home/sihanouk/crates/crates/a/Nargo.toml - does it exist?` without the fix.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [x] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
> Since the structure has Nargo.toml inside the crates folder, then members should direct to folders inside crates.

This isn't the case though.

```
├── crates
│   ├── a
│   │   ├── Nargo.toml
│   │   └── src
│   │       └── main.nr
│   └── b
│       ├── Nargo.toml
│       └── src
│           └── main.nr
├── Nargo.toml
└── Prover.toml
```

In this diagram `Nargo.toml` is on the same level as `crates` and so it doesn't sit inside of it. See this example https://github.com/noir-lang/noir/tree/master/test_programs/execution_success/workspace


Althought it does seem that the diagram as listed in the docs is incorrect, it should be:
```
├── crates
│   ├── a
│   │   ├── Nargo.toml
│   │   └── src
│   │       ├── main.nr
│   │       └── Prover.toml
│   └── b
│       ├── Nargo.toml
│       └── src
│           ├── main.nr
│           └── Prover.toml
│
└── Nargo.toml
```

**Comment by TomAFrench** [comment]
See https://github.com/noir-lang/noir/pull/4829

**Comment by TomAFrench** [comment]
Ah, yeah I chucked the `Prover.toml`s into the `src` folders by mistake.

**Review by TomAFrench — APPROVED** [review]
LGTM.

**Comment by iAmMichaelConnor** [comment]
Seems like I don't have permissions to re-open the closed issue

**Comment by TomAFrench** [comment]
Have you placed your `Nargo.toml` file inside of the `crates` directory? If so then you should move it up and out of that directory.

**Comment by TomAFrench** [comment]
The workspace structure in the docs are reflected in the tests with [here](https://github.com/noir-lang/noir/tree/master/test_programs/execution_success/workspace) which doesn't throw any errors if I run `nargo compile` from the workspace root.

**Pull request merged**
