### PR TITLE
fix: bigint builtins are foreigns

### LINKED ISSUE #6594: Some builtin functions are actually foreign
### Aim

Tried to implement the `bigint` functions (part of the `BlackBoxFunc` family) as `foreign` in #https://github.com/noir-lang/noir/pull/6551 , but they are marked as `#[builtin]` in Noir.

### Expected Behavior

Dispatching a builtin function to `Interpreter::call_builtin` should handle it, while foreign functions should go to `Interpreter::call_foreign`.

### Bug

There is no actual bug at the moment because there are redirects in the interpreter [[1](https://github.com/noir-lang/noir/blob/3cb4548115ce5ecbaeda389dd6aada03085c936d/compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs#L61), [2](https://github.com/noir-lang/noir/blob/3cb4548115ce5ecbaeda389dd6aada03085c936d/compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs#L238)], but it's a bit confusing. 

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

The redirect in the code from builtin to foreign handles the mislabeling.

### Additional Context

_No response_

### Project Impact

None

### Blocker Context

_No response_

### Nargo Version

_No response_

### NoirJS Version

_No response_

### Proving Backend Tooling & Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #6594

## Summary\*
I just changed the attribute, foreign and builtin are handled almost identically.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
We needed to take on some tech debt with this fallback handler here: https://github.com/noir-lang/noir/blob/b23e85bfbff4192d228bcaae4421d6cdfa5614f2/compiler/noirc_frontend/src/hir/comptime/interpreter/builtin.rs#L239-L241

We should remove this in this PR to make sure that we've got all of the instances of this issue.

**Comment by guipublic** [comment]
> We should remove this in this PR to make sure that we've got all of the instances of this issue.

Done

**Comment by guipublic** [comment]
I dont't understand why CI is failing on some boundedvev doc that is not modified here, but anyways I fixed the typo in the doc.

**Comment by TomAFrench** [comment]
> I dont't understand why CI is failing on some boundedvev doc that is not modified here, but anyways I fixed the typo in the doc.

Thanks, I think this got affected by the release PR which got merged.

**Review by TomAFrench — APPROVED** [review]

**Pull request merged**
