### PR TITLE
fix: Add compiler error message for invalid input types

### LINKED ISSUE #3062: Compiler panics on unsupported types to `main` rather than issuing a compiler error
### Aim

nargo --version
nargo 0.10.5 (git version hash: 91efe44d17762ea883d9a576d530049ad20f1393, is dirty: false)

git clone git@github.com:Savio-Sou/recursion-demo.git

nargo compile

### Expected Behavior

Success

### Bug

after fixing to:
fn main(
    verification_key : [Field], 
    proof : [Field], 
    public_inputs : [Field], 
    key_hash : Field, 
    input_aggregation_object : [Field; 16],
    proof_b : [Field],

nargo compile
The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: Params to the program should only contains numbers and arrays
Location: crates/noirc_evaluator/src/ssa/acir_gen/mod.rs:283

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml

### To Reproduce

1. See above
2.
3.
4.

### Installation Method

Binary

### Nargo Version

nargo 0.10.5 (git version hash: 91efe44d17762ea883d9a576d530049ad20f1393, is dirty: false)

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #3062

## Summary\*

This PR resolves a long standing panic which I've run into a lot and decided it is finally time to fix. Previously if an unsized type like a slice was used as an input to main, the program would panic with:

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: Params to the program should only contains numbers and arrays
Location: compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs:308

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
exit 101
```
Which is very confusing for users. I've added a proper check and error message during name resolution so that the error is now:

```
error: Only sized types may be used in the entry point to a program
   ┌─ /home/../short/src/main.nr:13:17
   │
13 │ fn main(fields: [Field], foo: NestedStructWithSlice) {
   │                 ------- Slices, references, or any type containing them may not be used in main or a contract function
   │

error: Only sized types may be used in the entry point to a program
   ┌─ /home/../short/src/main.nr:13:31
   │
13 │ fn main(fields: [Field], foo: NestedStructWithSlice) {
   │                               --------------------- Slices, references, or any type containing them may not be used in main or a contract function
   │

Aborting due to 2 previous errors
exit 1
```

Note that this check catches invalid types nested within generic structs as well.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
@sirasistant I believe the same checks here should apply for calling a Brillig function from an Acir function (and vice versa), can you confirm? If so, I can add it to this PR or in another.

**Comment by vezenovm** [comment]
It looks like this may break for array inputs that use globals.

**Comment by jfecher** [comment]
Ah, that's an important omission

**Comment by jfecher** [comment]
@vezenovm should be fixed now.

**Review by vezenovm — APPROVED** [review]

**Review by TomAFrench — APPROVED** [review]

**Pull request merged**
