### PR TITLE
create witness if needed

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Summary of changes

Create witness if needed when dividing expressions

# Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [ ] I have reviewed the changes on GitHub, line by line.
- [ ] I have ensured all changes are covered in the description.

### CODE REVIEW

**Comment by kevaundray** [comment]
Can you add more context to this PR and or link it to an issue?

**Comment by guipublic** [comment]
The user did not create an issue and I don't think we need one nor a regression as the fix is a no-brainer

**Review by jfecher — APPROVED** [review]
Looks good.
I agree on the not creating an issue/regression test argument. It would be nice if this were included in a test but going forward if we have a dedicated regression test for every issue we will have a test suite that is too large to practically test. Then we'd need to tackle the questions of only testing subsets of the test suite, which subset should be chosen, etc.

**Comment by kevaundray** [comment]
> Looks good.
> I agree on the not creating an issue/regression test argument. It would be nice if this were included in a test but going forward if we have a dedicated regression test for every issue we will have a test suite that is too large to practically test. Then we'd need to tackle the questions of only testing subsets of the test suite, which subset should be chosen, etc.

I was not suggesting a regression test, my question was about more context.

**Pull request merged**
