### PR TITLE
feat: let LSP work will with code generated by macros

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Code generated by macros (aztec_macros) ends up overlapping real code. The reason this happens is that, for example, this code is injected into a program:

```rust
let serialized_note = ...
```

The program above ends up with spans that are relative to that small snippet (for example `serialized_note` ends up in bytes  4..=19) and that might overlap some code that happens to be in that position in the same file. 

## Summary

In this PR we clear (set to a default of `0..0`) any spans that happen in generated code, if running in LSP mode. The result is that generated code doesn't overlap anymore with real code, and references, inlay hints, go to definition, etc., start working fine.

There's no need to stop showing inlay hints inside contracts, as there's no generated code that interferes there. 

## Additional Context

Maybe in the near future aztec macros will not be needed anymore. Implementing emptying spans is straight-forward so until that happens I think it might be worth having these LSP features work well when macros exist.

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by vezenovm — APPROVED** [review]
Would be nice if we had some state object for aztec macro transformers so you don't have to thread empty_spans through so many methods, but this code is soon to be removed either way so I don't think it is really worth the refactor and blocking this fix.

**Comment by jfecher** [comment]
Can you elaborate on the reason to pass `empty_spans` everywhere instead of just always issuing empty spans?

**Comment by vezenovm** [comment]
> Can you elaborate on the reason to pass `empty_spans` everywhere instead of just always issuing empty spans?
> I'm assuming we're worried about tracking callstacks within generated code for the purpose of building flamegraphs?

Not just flamegraphs I believe, as I remember the aztec team getting errors at the default span at the top of a file which could lead to confusion for users.

**Review by jfecher — APPROVED** [review]

**Comment by asterite** [comment]
> Can you elaborate on the reason to pass empty_spans everywhere instead of just always issuing empty spans?

I thought about that too, maybe an option to pass to the parser to produce empty spans instead of regular spans... but then we'd have to revert those changes if we stopped relying on these macros. With this way we'd just delete the unused code. I think I didn't want to make the parsing code more complex.

**Pull request merged**
