### PR TITLE
Split `util` module from noirc_frontend into new crate

### PR DESCRIPTION
**Pull request by TomAFrench**
# Related issue(s)

Addresses https://github.com/noir-lang/noir/pull/554#discussion_r1040007937

(Putting this through as a separate PR to simplify review)

# Description

## Summary of changes

`vecmap` and `btree_map` living in `noirc_frontend` prevents us from using them in any dependencies of that crate. This PR moves them into a `utils` crate which is intended to hold any non noir-specific helpers so that they can be used in the rest of the repo.

## Dependency additions / changes

No new external dependencies

## Test additions / changes

N/A

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

# Additional context

(If applicable.)

### CODE REVIEW

**Review by jfecher — APPROVED** [review]
Thank you!

**Comment by jfecher** [comment]
May need to remove + refresh the Cargo.lock file

**Comment by TomAFrench** [comment]
Actually, seems like it's trying to pull from https://github.com/AztecProtocol/barretenberg which I'm seeing as an empty repo. Not sure what's up.

**Comment by jfecher** [comment]
Apologies, had an internal discussion with the team and we want to avoid generic crate names like "util." Can we rename it to something less generic like `iter-extra`, `iter-extended`, `extra-iter`, etc? In the future this means if we want to add more utility functions/types to be used across the noir crates they will also need to be in their own crates.

The barretenburg issue seems to be related to a repository move that happened. I've tested this PR locally and found it to be working so this is perhaps not a blocker since it is a separate unrelated issue.

**Review by jfecher — APPROVED** [review]

**Pull request merged**
