### PR TITLE
chore: add ECDSA support to the aztec3-hacky branch

### PR DESCRIPTION
**Pull request by spalladino**
Cherry-pick the commits needed for ECDSA support to the aztec3-hacky branch, so we can use it from Noir contracts in Aztec.

### CODE REVIEW

**Comment by spalladino** [comment]
Tagging @sirasistant

**Comment by kevaundray** [comment]
Clippy errors originate from the branch itself, so this is fine.

-----

For reference + context; ECDSA was broken in the barretenberg backend and recently got fixed. 

Since it is not a Noir only error, we will also need to point to the version of barretenberg that introduces this fix. This is likely why the tests won't pass. 

We also cannot point to the latest barretenberg because I think this includes breaking changes between the version that the hacky branch points to and the version with the ECDSA fix.

It is definitely possible to patch an old version of barretenberg too and point to a branch in barretenberg, let me know if this is something you wish to pursue

**Comment by spalladino** [comment]
FWIW ECDSA is working fine [here](https://github.com/AztecProtocol/aztec-packages/blob/2eba0f033c6798efe76c6195546a97c03839b53c/yarn-project/noir-contracts/src/contracts/account_contract/src/main.nr#L32-L33) using this branch.

**Comment by kevaundray** [comment]
> FWIW ECDSA is working fine [here](https://github.com/AztecProtocol/aztec-packages/blob/2eba0f033c6798efe76c6195546a97c03839b53c/yarn-project/noir-contracts/src/contracts/account_contract/src/main.nr#L32-L33) using this branch!

Oh thanks for the correction :) 

I'm not quite sure why this works then since I also had to make a change in barretenberg too to make the verifier not panic + a few other miscellaneous fixes by Zac. If it's working on your end for the hacky branch though, then please feel free to ignore me :)

**Review by sirasistant — APPROVED** [review]

**Pull request merged**
