### PR TITLE
chore: add testcase for slice equality failing in comptime interpreter

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves 

## Summary\*

This PR adds a test case for #5273 which tracks whether the compile is properly handling comptime slice equalities. Once #5273 is fixed then it should be moved to `compile_success_empty`.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
This test needs to be exempted from the legacy tests for CI to pass.
I think we can just wait and add this test as part of https://github.com/noir-lang/noir/pull/5276 when it is expected to work though.

**Comment by TomAFrench** [comment]
I've added an entry to ignore the legacy test.

**Review by jfecher — CHANGES_REQUESTED** [review]
I don't see why we're adding a failing test now rather than waiting until we add a PR to fix it to add the passing test like we usually do?

**Comment by TomAFrench** [comment]
My thinking on this is it's generally just observability. Tests become us asserting that the compiler does what we expect rather than just "working correctly". This ensure that if the behaviour of the compiler changes in future then we'll be aware of it.

**Comment by jfecher** [comment]
@TomAFrench I can see that argument, but doesn't it apply to all known issues? I think we should just wait until traits / operator overloading is implemented in the interpreter to add this test since I don't see it being accidentally added.

**Pull request closed without merging**
