### PR TITLE
chore: Fix Search Input Visibility in Dark Mode

### PR DESCRIPTION
**Pull request by joaolago1113**
### Summary
This pull request addresses an issue with the search input box on the Noir documentation site when in dark mode. The text within the search box is illegible due to the white background color, which conflicts with the white text color.

### Problem Description
In dark mode, the background color of the search input box remains white, while the text color is also white, rendering the text invisible to users. This creates a poor user experience as it prevents users from seeing what they are typing into the search box.

### Solution
To fix this issue, the background color of the search input box has been changed to transparent, allowing for the text to be visible in both light and dark modes.

#### Desktop Dark Mode

| Input State | Screenshot |
|-------------|------------|
| Text Entered, Barely Visible | <div  style="text-align: center;">Text barely visible in search box on desktop dark mode</div> |

#### Mobile Dark Mode

| Input State | Screenshot |
|-------------|------------|
| Text Entered, Barely Visible | <div style="text-align: center;">Text barely visible in search box on mobile dark mode</div> |

### Visual Comparison

| Mode     | Before Change | After Change |
|----------|---------------|--------------|
| Dark - Desktop | <div style="text-align: center;">Before Desktop Dark</div> | <div style="text-align: center;">After Desktop Dark</div> |
| Light - Desktop | <div style="text-align: center;">Before Desktop Light</div> | <div style="text-align: center;">After Desktop Light</div> |
| Dark - Mobile | <div style="text-align: center;">Before Mobile Dark</div> | <div style="text-align: center;">After Mobile Dark</div> |
| Light - Mobile | <div style="text-align: center;">Before Mobile Light</div> | <div style="text-align: center;">After Mobile Light</div> |

### Files Changed
- `docs/src/css/custom.css`: Added styles to override the default background color of the `#docsearch-input` element.

### Testing
The changes have been tested across various browsers and devices to ensure compatibility and that the search input box text is now clearly visible in both light and dark modes.

### CODE REVIEW

**Comment by TomAFrench** [comment]
Please don't update the branch unless there's a merge conflict (which is very unlikely to happen on the docs). It just chews up CI time for no reason.

**Review by jfecher — APPROVED** [review]
LGTM

**Comment by jfecher** [comment]
CC @noir-lang/developerrelations

**Review by critesjosh — APPROVED** [review]
thank you!

**Pull request merged**
