### PR TITLE
chore(docs): codegen reference docs for `nargo` CLI

### LINKED ISSUE #4136: Document `nargo compile --force`
Document https://github.com/noir-lang/noir/pull/4054.

Possibly on the Reference page: https://noir-lang.org/docs/reference/nargo_commands#nargo-compile

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #4136 
Resolves https://github.com/AztecProtocol/dev-rel/issues/128
## Summary\*

This PR codegens the reference material for the nargo CLI to avoid us having to copy documentation from the code over to a markdown file.

The exact format of the codegenned markdown isn't final and we can iterate on this but it guarantees completeness.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [x] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by Savio-Sou** [comment]
cc @noir-lang/developerrelations

**Comment by signorecello** [comment]
Thank you, this is exactly what we needed!

Now if we only could do the same for the stdlib, that would allow for that explanation/reference separation @noir-lang/developerrelations would like to have. But that's not possible at this point, due to the fact the stdlib is Noir so CLAP shouldn't work there.

Our end goal is for engineers to simply incorporate some decorators with their code and don't have to think much about the docs.

**Comment by TomAFrench** [comment]
Also looked at https://github.com/clap-rs/clap/tree/master/clap_mangen but there's no easy way to display roff in docusaurus so we'd have to go down the route of https://github.com/jgm/pandoc.

If we go down that route then we'd lose any control over how we display this information so it's probably best to just use `clap_markdown` as we can modify that as necessary.

**Comment by TomAFrench** [comment]
image
Yeah, I realise I'm breaking the warning I wrote in `deny.toml`, it's fine for now as we're not publishing `nargo_cli` to crates.io anyway.

**Review by critesjosh — APPROVED** [review]
lgtm!

**Review by signorecello — APPROVED** [review]

**Pull request merged**
