### PR TITLE
chore(fmt): fix emit comments

### PR DESCRIPTION
**Pull request by f01dab1e**
# Description

# Problem

pre
```rust
fn hello() {
    1; // 42
     2
}
```

post:
```rust
fn hello() {
    1; 
    // 42
    2
}
```

pre
```rust
// lalalalalalalal
contract Uniswap {}


```

post:
```rust
// lalalalalalalal contract Uniswap {}
```

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by kevaundray** [comment]
can you write a description to say what is being fixed here and or open up an issue?

**Comment by f01dab1e** [comment]
cc @kevaundray @jfecher

**Comment by kevaundray** [comment]
> post: // lalalalalalalal contract Uniswap {}

Is this correct? It comments out the contract uniswap part

**Comment by kevaundray** [comment]
Aht the test is not actually doing that though

**Review by kevaundray — APPROVED** [review]

**Comment by f01dab1e** [comment]
I wrote in the problem section, this is how I formulated it before.  but I found other problems - moved them to draft

**Comment by f01dab1e** [comment]
I wrote in the problems section, this is how it was formatted before.  but found other problems - moved them to draft

**Review by kevaundray — APPROVED** [review]

**Pull request merged**
