### PR TITLE
chore: Perform formatting changes to integration tests

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves 

## Summary\*

This PR takes all of the integration test changes from #2137 so they can be merged separately.

These changes are a noop, generally removing unused imports and performing formatting changes.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by kevaundray — APPROVED** [review]

**Comment by TomAFrench** [comment]
> Thats me done for today

**Comment by kevaundray** [comment]
> > Thats me done for today

Finally good ser -- enjoy your weekend!

**Comment by TomAFrench** [comment]
Was more meant as a dig at you popping up at this ungodly hour but yeah, gonna stop now too.

**Comment by TomAFrench** [comment]
Enjoy your long weekend!

**Pull request merged**
