### PR TITLE
chore(docs): autogeneration of NoirJS docs

### LINKED ISSUE #3199: Auto-generate NoirJS docs
### Problem

We all spend too much time manually changing reference material like methods, interfaces, commands, for NoirJS.

### Happy Case

We can leverage existent tooling (i.e. TypeDocs) to auto-generate this documentation in a markdown format

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by signorecello**
# Description

This PR adds autogenerated docs for NoirJS packages, using Typedoc

## Problem\*

We're spending way too much time changing function signatures and similar stuff. We should be able to rely on autogeneration for that.

Resolves #3199

## Summary\*

- Adds and configures two plugins to docusaurus in order to generate sidebars, and make the return of typedoc be formatted in markdown
- Exports types from noir_js and backend_barretenberg so they are documented, [apparently this is the only way of documenting the types](https://github.com/TypeStrong/typedoc/issues/516). I find Typedoc too opinionated, but afaik there's no better tool

## Additional context

I hacked around a bunch of `ignores` here and there, they'd tipically be made private but for some reason they aren't so I'm manually ignoring them. Again, Typedoc expects code to be written in a certain format in order to be documented in a certain way

### CODE REVIEW

**Comment by signorecello** [comment]
These docs builds fail and will continue to fail because they depend on other package's build processes. Unfortunately netlify doesn't really provide a way to define a better CI process.

However #3296 already solves this by building with the Github CI. So let's block this one until we merge that, and I'll figure out then

**Comment by signorecello** [comment]
gtg @Savio-Sou

**Comment by critesjosh** [comment]
Is it possible to autogenerate links to the source code on github?

**Review by Savio-Sou — APPROVED** [review]
This is incredible. Thank you @signorecello!

**Pull request merged**
