### PR TITLE
chore: fixing some broken links

### PR DESCRIPTION
**Pull request by signorecello**

### CODE REVIEW

**Review by critesjosh — APPROVED** [review]

**Comment by jfecher** [comment]
@TomAFrench @signorecello looks like there are broken docs links on master now possibly related to this PR. See https://github.com/noir-lang/noir/pull/4560 and https://github.com/noir-lang/noir/pull/4523 which are failing the build docs step.

The links that are failing are:
```
Error: Docs markdown link couldn't be resolved: (../reference/NoirJS/noir_js/type-aliases/ForeignCallHandler.md) in "/home/runner/work/noir/noir/docs/versioned_docs/version-v0.25.0/explainers/explainer-oracle.md" for version v0.25.0

Error: Docs markdown link couldn't be resolved: (../reference/NoirJS/noir_js/type-aliases/ForeignCallHandler.md) in "/home/runner/work/noir/noir/docs/versioned_docs/version-v0.25.0/how_to/how-to-oracles.md" for version v0.25.0

Error: Docs markdown link couldn't be resolved: (../reference/NoirJS/noir_js/index.md) in "/home/runner/work/noir/noir/docs/versioned_docs/version-v0.25.0/how_to/how-to-recursion.md" for version v0.25.0
```

**Comment by jfecher** [comment]
> possibly related to this PR

Doesn't look like this PR touches any of those links though. Not sure why they are broken now.

**Comment by signorecello** [comment]
Don't seem related, no... I'll have a look

**Comment by signorecello** [comment]
Ok this is worse than I thought, for some reason typedoc didn't build...

**Pull request merged**
