### PR TITLE
chore!: Remove keys from preprocessed artifacts

### LINKED ISSUE #2280: Remove storage of pk/vks from artifacts
This is required for https://github.com/noir-lang/noir/issues/2164 as now barretenberg specifies how the keys are being written to file.

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #2280 
## Summary\*

We no longer have keys in with the preprocessed artifacts as barretenberg will be in charge of writing these to file from now on.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by kobyhallx — DISMISSED** [review]

**Review by phated — DISMISSED** [review]
How do you name pk and vk for each contract function?

**Comment by TomAFrench** [comment]
"That's the neat part, you don't"

Contracts are never executed, let alone proven against so we never need the pk/vk for them. We're not writing any keys for programs either as we calculate them each time before we use them.

**Comment by TomAFrench** [comment]
There's definitely some tech debt being taken on here but I think we can clean that up as we get further into the dynamic backends epic.

**Comment by TomAFrench** [comment]
Let's hold off on this until post 0.10.0

**Review by phated — DISMISSED** [review]
This is a breaking change and we need to release 0.10.5 first

**Pull request merged**
