### PR TITLE
chore: Update `noir-source-resolver` to v1.1.3

### PR DESCRIPTION
**Pull request by signorecello**
Updating noir-wasm to point to noir-source-resolver version 1.1.3

### CODE REVIEW

**Comment by kevaundray** [comment]
@jonybur or @signorecello is there something blocking this from being merged?

**Comment by jonybur** [comment]
@kevaundray Not that I know of

**Comment by kevaundray** [comment]
> @kevaundray Not that I know of, shall I go ahead with this?

Yep! If it all looks good to you, please merge

**Comment by TomAFrench** [comment]
This includes the fix from https://github.com/noir-lang/noir-source-resolver/pull/5

**Review by TomAFrench — APPROVED** [review]

**Pull request merged**
