### PR TITLE
Change unused variables to warnings

### PR DESCRIPTION
**Pull request by jfecher**
Changes the unused variable error to a warning since they should be optimized out by the ssa pass anyway. This affects all variables, even parameters to main.
This is also noir's first warning instead of a hard error so some small plumbing was added to implement warnings.

### CODE REVIEW

**Review by guipublic — APPROVED** [review]

**Comment by kevaundray** [comment]
I think we still want it to be an error and not by default optimised out by the compiler. An unused variable signals an unused constraint, which is most likely a bug.

There can be a flag in the future to ignore it for development mode

**Comment by jfecher** [comment]
What is the unused constraint in the ssa pass? It was my impression that it only affected the interpreter.

I still think it should be a warning since it is only an efficiency concern. When debugging quick changes fixing these are secondary and slow down the developer. The warning is also annoying enough that it will be fixed eventually still to silence it, thus removing the extra constraint then.

**Comment by kevaundray** [comment]
In the interpreter it would have been fine to also have unused constraints. The unused constraint is indicative of a bug in the business logic of your code which is why it is a error right now. 

Since it's not just an efficiency concern, it would be better if users had to opt out of it explicitly

**Comment by jfecher** [comment]
I don't see why the unused constraint would be indicative of a bug anymore than an used variable would be indicative of a bug in classical languages. It is true that many times it is - and that is why we still have it as a warning. Many times it is just a mistake left in while debugging though.
For prior art here, Go also errors if there are any unused variables and it is considered a mistake due to the large impact it has on debugging speed.

**Comment by kevaundray** [comment]
For constraint systems, the biggest source of bugs will be missing constraints, not using a variable is a subclass of this that we should guard against. In classical languages, I think it also makes sense to not release code into production, if there are unused variables.

For golang, I agree that it affects debugging speed, which is why I was suggesting to allow the user to opt out of it when in debug mode

**Review by kevaundray — CHANGES_REQUESTED** [review]
Adding request changes review; details are listed above

**Comment by guipublic** [comment]
Unsued variables is a source of missing constraint when you manually write your own constraints. With Noir, the compiler writes the constraints for you and it does not forget one. So using Noir is the best way to solve the missing constraint problem. To that regard, I think unsued variables should be treated as they usually are by other programming languages, i.e as a warning.

**Comment by jfecher** [comment]
Looks like the merge from #479 is now requiring a large, prohibitively expensive merge from master. I'll revert it and see if I can't cherry pick the necessary changes.

**Pull request closed without merging**
