### PR TITLE
feat: Add ACIR serializer C++ codegen

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves 

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
The breaking bump in bincode may be unnecessary. Checking now

**Comment by kevaundray** [comment]
> The breaking bump in bincode may be unnecessary. Checking now

I remember fiddling with it and to get the same behaviour I had to bump the version and use "legacy" mode

**Comment by TomAFrench** [comment]
I've added some docs on what these tests mean and how to regenerate the codegened files.

I think it would be a good idea to assign some codeowners to the `codegen` folder to avoid breaking changes being made to the serialisation without some thought going into it.

**Comment by kevaundray** [comment]
> I've added some docs on what these tests mean and how to regenerate the codegened files.
> 
> I think it would be a good idea to assign some codeowners to the `codegen` folder to avoid breaking changes being made to the serialisation without some thought going into it.

We can add you and me initially and or anyone else who knows how to update bb

**Review by kevaundray — APPROVED** [review]

**Pull request merged**
