### PR TITLE
feat(stdlib)!: eddsa function using turbofish

### LINKED ISSUE #4514: Re-work eddy in the stdlib for hasher trait when turbo fish is implemented
### Problem

eddsa_verify_with_hasher (from PR #4440) is taking a hasher as parameter. However the hasher can have some pre-seeded state which will muck with the verification algorithm.

### Happy Case

We should rather instantiate a new hasher inside the function:

```
pub fn eddsa_verify_with_hasher<H>(
    pub_key_x: Field,
    pub_key_y: Field,
    signature_s: Field,
    signature_r8_x: Field,
    signature_r8_y: Field,
    message: Field,
) -> bool 
where H: Hasher + Default {

```
and then we can rename it to: `eddsa_verify<H>`

### Project Impact

None

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Resolves #4514 

## Summary\*

This updates `eddsa_verify_with_hasher` to have the following signature now that we support the turbofish operator:
```rust
pub fn eddsa_verify_with_hasher<H>(
    pub_key_x: Field,
    pub_key_y: Field,
    signature_s: Field,
    signature_r8_x: Field,
    signature_r8_y: Field,
    message: Field
) -> bool 
where H: Hasher + Default {
  [function body ...]
}
``` 
This re-work was only possible with further bug fixes from https://github.com/noir-lang/noir/pull/5049 and https://github.com/noir-lang/noir/pull/5041. The original turbofish PR can be found here (https://github.com/noir-lang/noir/pull/3542).

## Additional Context

This PR can most likely be merged into its parent #5049 but I just made this separate PR to separate the bug fix and the stdlib library breaking change.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [x] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
I'm inclined to just rename this to `eddsa_verify` at this point.

**Comment by TomAFrench** [comment]
I'm good with merging this after the rename. Holding off to avoid messing up the diff of other PRs.

**Review by jfecher — APPROVED** [review]
LGTM

**Comment by vezenovm** [comment]
> I'm inclined to just rename this to `eddsa_verify` at this point.

Renamed it

**Pull request merged**
