### PR TITLE
fix: SSA typing for loop bounds

### PR DESCRIPTION
**Pull request by sirasistant**
# Description

## Problem\*

Partial work towards https://github.com/noir-lang/noir/issues/4275

## Summary\*

The frontend is not enforcing typing on loop bounds in some cases:
```
fn loop_from<N, K>(_arr: [Field; N], _another: [Field; K]) -> u32 {
    let mut acc = 0;
    // N and K are type Field but the iterator is u32
    for i in N..K {
        acc += i;
    }
    acc
}

fn main() -> pub u32 {
    loop_from([0; 10], [0; 20])
}
```
This PR casts the types of the bounds at the SSA level with the iterator type but we might want to enforce this in the frontend instead. I think the mismatch only happens on generic bounds so it might be painful to fix.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by jfecher — CHANGES_REQUESTED** [review]
The frontend does unify the type for loop bounds. The issue is related to https://github.com/noir-lang/noir/pull/4118 where the frontend does not actually have a type for "any integer except Field." Once that PR is fixed & merged this issue should be fixed as well.

**Comment by sirasistant** [comment]
Oh, I think your message in that PR addresses exactly that

**Comment by sirasistant** [comment]
@jfecher @jzaki  just tested on master after https://github.com/noir-lang/noir/pull/4118 was merged and we still have different types in the example in the description:
```
Types of loop: index Numeric(Unsigned { bit_size: 32 }), start Numeric(NativeField), end Numeric(NativeField)
```

**Comment by jfecher** [comment]
@sirasistant yep, sorry that is expected. We decided to split that PR into one that adds the new type variable kind, and then another later PR to use the new type variable kind in for loops and bitwise operations. I'll update this thread when the second PR is up

**Comment by jfecher** [comment]
@sirasistant https://github.com/noir-lang/noir/pull/4376 should fix the issue

**Comment by sirasistant** [comment]
fixed in https://github.com/noir-lang/noir/pull/4386

**Pull request closed without merging**
