### PR TITLE
feat: add `min` and `max` functions to the stdlib

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves https://github.com/noir-lang/noir/issues/4781

## Summary\*

This PR adds an equivalent to Rust's `std::cmp:max` and `std::cmp::min` https://doc.rust-lang.org/src/core/cmp.rs.html#1209

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by jfecher — COMMENTED** [review]
Looks good. Just needs docs changes.

We may also want to consider adding these as a default method on the Cmp trait.

**Comment by TomAFrench** [comment]
> We may also want to consider adding these as a default method on the Cmp trait.

I looked at implementing this but I'm getting a stack of errors related to the trait bound.

```
trait Ord {
    fn cmp(self, other: Self) -> Ordering;

    fn max(self, other: Self) -> Self {
        max(self, other)
    }
}
```

results in 
```
No matching impl found for `T: Ord`
No matching impl found for `T: Ord`
No matching impl found for `A: Ord`
No matching impl found for `A: Ord`
No matching impl found for `A: Ord`
No matching impl found for `A: Ord`
```

**Comment by jfecher** [comment]
@TomAFrench ah, I guess we don't automatically assume `Self: Trait` within the definition for `Trait`.

**Comment by TomAFrench** [comment]
Yep, lemme check if we have an issue for this already.

**Comment by TomAFrench** [comment]
Ah, too late.

**Pull request merged**
