### PR TITLE
chore(docs): making release-please commit new version to the repo

### PR DESCRIPTION
**Pull request by signorecello**
# Description

This PR makes release-please also trigger a commit with the new docs version

## Problem\*

After the changes in the release-please to cut new versions, dumb me forgot to make it actually commit the files to the repo

### CODE REVIEW

**Comment by TomAFrench** [comment]
This is going to absolutely murder my notifications with all the comments on each commit.

**Comment by signorecello** [comment]
I mean it comments only when there are changes in the docs I think?

**Comment by signorecello** [comment]
btw this is ready 👍

**Review by Savio-Sou — APPROVED** [review]
Approving and merging this in to help push v0.19.0 docs out.

Let's improve comment spam (if any) with follow up PRs.

**Pull request merged**
