### PR TITLE
fix: workaround for LSP dependency resolution

### PR DESCRIPTION
**Pull request by ludamad**
# Description

This is currently not ideal in form but should inform a larger fix. There was a desire to get it into master soon.

## Problem\*
https://github.com/noir-lang/noir/issues/1838 will take some time for a larger fix, meanwhile there was a desire for a solution for the current Noir dogfooding.

## Summary\*

Works around issues by:
1. Loading from main.nr or lib.nr as appropriate instead of just any entry point
2. Filtering errors based on the the file pased
3. Loading Nargo.toml dependencies which are used in aztec contracts

# PR Checklist\*

- [*] I have tested the changes locally.
- [*] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by phated — CHANGES_REQUESTED** [review]
I'm currently making movement on #1838 so I don't think we should merge this

**Comment by charlielye** [comment]
@phated any timeline on your branch? any reason we can't merge this now so we can all get the benefit, and then revert/replace once your stuff is ready? would speed us up.

**Review by dbanks12 — COMMENTED** [review]
Tested and all appears to be working nicely in VSCode on this branch!

**Review by kobyhallx — APPROVED** [review]
Approving ad temp solution, thanks Adam!

**Pull request merged**
