### PR TITLE
feat: Sync from aztec-packages

### PR DESCRIPTION
**Pull request by AztecBot**
Automated pull of Noir development from [aztec-packages](https://github.com/AztecProtocol/aztec-packages).
BEGIN_COMMIT_OVERRIDE
feat: Added indirect const instruction (https://github.com/AztecProtocol/aztec-packages/pull/8065)
feat: optimize to_radix (https://github.com/AztecProtocol/aztec-packages/pull/8073)
feat: automate verify_honk_proof input generation (https://github.com/AztecProtocol/aztec-packages/pull/8092)
feat: Sync from noir (https://github.com/AztecProtocol/aztec-packages/pull/8093)
feat: Poseidon2 gates for Ultra arithmetisation (https://github.com/AztecProtocol/aztec-packages/pull/7494)
feat: Sync from noir (https://github.com/AztecProtocol/aztec-packages/pull/8008)
feat: Add reusable procedures to brillig generation (https://github.com/AztecProtocol/aztec-packages/pull/7981)
feat: Small optimization in toradix (https://github.com/AztecProtocol/aztec-packages/pull/8040)
feat: unify all acir recursion constraints based on RecursionConstraint and proof_type (https://github.com/AztecProtocol/aztec-packages/pull/7993)
feat: Sync from noir (https://github.com/AztecProtocol/aztec-packages/pull/7958)
END_COMMIT_OVERRIDE

### CODE REVIEW

**Comment by TomAFrench** [comment]
This is blocked by a new `bb` release.

**Review by TomAFrench — APPROVED** [review]

**Comment by TomAFrench** [comment]
@asterite did you make any change to the lsp in aztec-packages or are all these change just merge conflicts?

**Comment by asterite** [comment]
@TomAFrench I didn't make changes here... but for some reason some of the LSP files always give a conflict when merging, I don't know why (it happened in the past too).

**Comment by TomAFrench** [comment]
Cool, I'll just revert all these in that case.

**Comment by asterite** [comment]
Sounds good. What I usually do is to checkout the version in noir and copy-paste the file and commit that... I don't know if that's what you did.

**Comment by asterite** [comment]
Well, "usually", I think I just did it once 😅

**Pull request merged**
