### PR TITLE
feat: add support for writing tracing debug info to file

### PR DESCRIPTION
**Pull request by kobyhallx**
# Description

## Problem\*

Turning rtacing on/off by adding code each time is cumbersome.

## Summary\*

Allows to turn tracing on by defining `env` `NARGO_LOG_DIR` = `/path/to/directory/with/logs/`

Our own tracing would be aded gradually on as needed basis. By enabling this we still benefit from other crates using tracing.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by kevaundray** [comment]
> Turning rtacing on/off by adding code each time is cumbersome.

Can you say why we are adding this and removing env_logger?

**Comment by TomAFrench** [comment]
Yeah, I'd be fine adding this on top but removing `env_logger` would make getting logs from users more cumbersome I think. Past the extra steps involved, most of the output I see is from setting up the wasm so we'll probably end up in a situation where they can't directly post the log but do a file upload.

I'm not a huge fan of the idea of downloading files from unknown sources when we could get a more reasonable output by just setting the log level like before.

**Comment by kobyhallx** [comment]
I've actually did not meant to drop `env_logger` here. This should come later.

48bf364: chore: restore env_logger

**Review by TomAFrench — APPROVED** [review]
LGTM

**Comment by Savio-Sou** [comment]
Is this feature intended to be used by Noir devs?

**Pull request merged**
