### PR TITLE
feat: Implement print method

### PR DESCRIPTION
**Pull request by grasshopper47**
# Description

## Problem\*

Resolves https://github.com/noir-lang/noir/issues/3575

## Summary\*

Adds `print` method alongside `println` to ease printing in special use-cases, such as elements of slices.
Updates appropriate tests, and `logging.md` documentation.
Add a subchapter to `03_string.md` documentation for the `fmtstr` type

## Documentation\*

Check one:
- [ ] No documentation needed.
- [x] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by vezenovm — COMMENTED** [review]
Looks good. Could you also add a couple print tests to `nargo_cli/tests/execution_success/strings`?

**Review by jfecher — COMMENTED** [review]
If we add a `print` function, I think we should reimplement `println` in terms of that so that we only have 1 primitive instead of two. `println` could be rewritten as
```rs
unconstrained pub fn println<T>(input: T) {
    print(input);
    print("\n");
}
```

**Comment by jfecher** [comment]
> Would [snippet] be a quicker alternative than 2 calls?

Possibly, I'm not quite sure. Feel free to go with whichever approach is easier / more straightforward.

**Comment by TomAFrench** [comment]
I think this would be preferable to avoid multiple foreign calls being performed.

**Comment by grasshopper47** [comment]
> I think this would be preferable to avoid multiple foreign calls being performed.

It creates a problem: what if you pass a `fmtstr` down to `println`, and it passes that down to `print` ... formatted format strings cannot be printed:

image

I get the crash above when I run a personal test Noir project through the newly built compiler  

I'm surprised this isn't caught at test-time....

As specified in the docs, I ran `nix flake check -L`, thinking this is how to run the tests. There are countless `std::println(f"` statements in the .nr tests, why didn't I get an error during testing?

**Comment by grasshopper47** [comment]
> I think this would be preferable to avoid multiple foreign calls being performed.

Pending a reply on the previous point, I have another suggestion:

image

image

Let me know if this is the right idea and I can commit it

**Comment by jfecher** [comment]
@grasshopper47 format strings should be able to be printed. If I had to guess what was happening, when you switched println to print, we're missing an explicit check for `Println` to handle format strings before it is actually called. That check, along with any others, would need to be changed to check for Print instead. Alternatively, I'm fine with the oracle change as well. Although we should name the intermediate value to make it more obvious what it represents E.g. `print_newline`.

**Comment by grasshopper47** [comment]
> @grasshopper47 format strings should be able to be printed. If I had to guess what was happening, when you switched println to print, we're missing an explicit check for `Println` to handle format strings before it is actually called. That check, along with any others, would need to be changed to check for Print instead. Alternatively, I'm fine with the oracle change as well (we'll just need to test it to make sure it still works for tuples). Although we should name the intermediate value to make it more obvious what it represents E.g. `print_newline`.

Format strings ARE printable. the Problem with using `print(f"` is that gets passed to the oracle method as doubly formatted string, and sorting that out in `execute_print` would be (needless) extra work IMO

How do I run the tests so that I make sure to not have failing checks here?

**Comment by jfecher** [comment]
> I need to understand how to run the tests in order to check, can you help out?

You should be able to run them all with `cargo test` locally

**Comment by grasshopper47** [comment]
> > I need to understand how to run the tests in order to check, can you help out?
> 
> You should be able to run them all with `cargo test` locally

If that would work, I would not be going around and asking silly questions. Look-see:

image

**Comment by grasshopper47** [comment]
> @grasshopper47 it runs past that point for me locally. Do you have `clang`, the c++ stdlib, and `libomp` installed? If you have nix/direnv I would have thought that'd be handled for you.

Clang install did the trick, many thanks!

**Comment by grasshopper47** [comment]
@jfecher Something wonky about this branch, I remade it. 

It contains all the changes requested here.

**Pull request closed without merging**
