### PR TITLE
chore!: Update to `acvm-backend-barretenberg` v0.12.0

### PR DESCRIPTION
**Pull request by kevaundray**
# Description

This is the counterpart to https://github.com/noir-lang/acvm-backend-barretenberg/pull/239

## Problem\*

Resolves 

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by kevaundray** [comment]
To note: proving keys and verification keys are no longer governed by nargo. However since barretenberg does not produce the proving key as an artifact as of writing, this will lead to a slow-down in proving and verification

**Comment by TomAFrench** [comment]
Rebasing this on top of #2283

**Comment by TomAFrench** [comment]
Nargo prove output is currently broken
```
$ nargo prove
Ok(Output { status: ExitStatus(unix_wait_status(0)), stdout: "[ 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 03 15 1a 56 58 0a cc 36 0f 25 36 11 24 8d 09 e5 24 2c 2e fe 0b ca 39 4d 63 e1 b4 a9 2b ab 4e f7 6c cc 0a fc 03 df 9e b4 a2 d2 f0 08 3d 62 e8 aa a8 4d 0f f0 35 85 ec a3 a6 0a 27 42 5f f0 ec 36 8c ae 28 e2 7b 10 4a e9 de a9 8d af b4 f5 02 af 8f 3b b3 85 78 dc d1 49 59 4a 3c e2 6b 2e 0e 8a 0b 47 27 a2 a1 55 d5 37 f0 7c a3 b3 e6 7e 58 01 93 c2 bc e3 bf b0 87 38 84 87 ce ee 48 ba 2d d3 d4 ca 23 ce 0c 2d 8e 0f 77 8a 39 03 9e 5f 21 69 99 74 eb 45 e4 86 f5 ed 23 54 8c fa de 47 39 94 c9 ca 04 26 ee 0e fa 8c b0 cd 46 29 8e c2 8d d7 2c 38 59 88 c4 d6 af b3 72 c6 2a 03 02 ba 71 ff 6e ce 2e e0 9b 04 c3 44 d3 c6 64 3c 87 74 f8 3e 6d ad 0d 6c 3f 69 97 d5 c1 fe bb f6 9f 15 99 df 33 96 0d 9f 50 82 62 df d1 8a af 5c e3 33 16 e1 ed 3e 5a 9b 88 42 ae 09 8b b9 11 fe 1b 28 10 2f 26 a0 1f f0 bf 06 0e 48 cc 7d 9e 8c 30 9c 01 d1 99 59 ae 4b b9 a2 b5 99 2b e5 df 7d cf 66 1e 49 99 af 15 b2 4b ce 63 42 e8 5e 08 60 71 65 29 c9 94 2f b8 88 6c cb ab 49 70 98 31 d2 59 f0 f0 75 80 32 0e a1 43 22 1e a1 4c 49 ca 34 61 49 d1 95 25 95 ec e0 9b 5b 45 3f ff 39 22 46 2e c5 fe 94 d2 5c 2d 86 a5 51 5b 31 1b 5e f7 bc 0d f8 73 dd cb b6 44 da 87 d6 28 4d 81 32 ea 2c 72 e8 03 c4 29 26 13 0f 26 47 1c 3c b0 d5 36 66 0b 7c 1a 6a 4b d0 9f b7 c1 f9 34 3f 75 3b 52 9b 4a d7 64 24 7b b6 0d 03 e2 0b f1 c5 35 14 8f 65 62 1b 67 04 03 94 7e ef 91 09 c0 d6 be 3a 9a df 42 ad 8b dd a7 b9 25 4f 7b c6 72 67 ae 50 6c 33 d9 07 97 3d 45 56 3f 8a 4d 42 09 49 b8 13 1f 8a 69 66 85 d4 82 9c 05 e8 9b 64 39 4c 23 d1 9f f0 c1 5b 61 20 2d bf 69 2b 40 09 f9 80 67 5f 73 63 1c 93 61 e1 b9 dc 08 86 32 00 e4 2d 7d 8b 4d 17 22 64 a0 d6 1a a7 ea fb 3c 73 46 91 06 7c 11 5d 6a e5 2c 94 52 15 13 91 81 1f 19 a5 eb 66 7d 99 f8 56 22 d2 40 12 30 c5 62 a9 e1 50 ff b5 17 1c 9d 9a 47 0d 67 77 11 30 d8 61 3a fd 15 b2 3a ac b1 a1 ed 40 0f 13 8e 1b 18 14 33 94 18 b9 8e 31 57 26 5d e2 fd 7d 2d 29 ab e3 be 4e 3e 4d 95 e9 8a 04 c8 d3 e7 5f f1 74 25 75 02 e9 6f 2d 13 1c 4c ac e5 ce aa a0 21 ec 5b 32 54 50 08 b6 4f 12 53 fa b6 bd 36 27 7b 6d 0a c3 84 7e 6d 3b 68 fb 01 53 0f a9 08 ce 1e 59 1e 2c 95 97 fe 96 44 3f de c0 11 65 24 9b 42 90 df c1 92 a0 c4 31 2e 23 4f 09 3c 61 3a fb 19 c7 fb bd 5b 07 19 da ea d6 5b 70 c2 6f da 13 1d 13 bf ec fb 23 4d f6 d8 a0 93 88 6e 8c 83 5e 18 9c 63 64 27 df 34 07 4f b8 26 a1 99 35 86 9d 2e eb ee 8b 58 e3 8b 54 3e fb bb b9 27 44 55 a9 16 29 69 13 c7 27 88 fb 06 a6 ce fa 8f 31 0c ed 90 9d dc 16 bb f1 46 81 8e 44 c2 6f d8 14 5d 86 0b 2a d2 5d 17 95 c0 30 60 f0 ad 7e 97 f0 02 10 d9 ec b3 74 4e 43 cf 16 ce d0 1b 94 0f 6e 60 d2 0a 5e ef 07 83 94 17 fa cb 4e aa 33 8f 2d 1c f3 b2 32 a9 b5 57 b1 d0 36 de 57 b2 82 3c fd 62 63 17 0c 39 2b 94 ce 49 4d 3b 8e 7a 6d 13 86 eb 79 2b 32 66 95 9d 63 31 b2 e7 dd d5 65 81 56 87 6a 26 f5 7d b7 70 31 38 8e 4f 3c 6d 86 a8 de c3 66 2e a2 46 f6 7c 16 00 c5 0c 09 d0 01 ed 8b cc d5 28 05 e1 64 cd 19 e9 f3 00 b9 32 09 62 5f 10 10 84 ac f0 62 1b 87 15 26 13 55 67 6b 09 63 3b 67 18 a6 d1 8a 53 4e e7 1e db a2 cd 4e 31 3d 73 cf 6e b1 c4 1e ab d5 b2 fa f4 01 ec 01 39 53 7e ad 1b 19 15 24 fc c4 a4 97 83 0b 0b 28 08 68 36 8c 35 b2 de 06 d8 eb a9 14 86 eb 52 56 c6 f1 d5 51 05 28 38 56 2f 01 b2 82 59 4f ea e1 f5 a7 53 a5 1d 3d b7 7e a1 13 aa 98 63 0f a1 60 ce 9d 27 78 01 8e 8b 22 65 4b 21 eb da 15 c2 9a df af bd fa 17 66 f5 b4 7c b5 fc c9 a6 38 f5 a4 51 e0 16 b0 18 fb 75 92 b3 8c 32 de ee 31 bd e2 50 bd 2f 14 f2 82 82 51 e1 c3 6e 72 a1 66 b8 9e db 56 28 01 24 9b a2 dd 1d 88 3e fd c8 15 ef 54 35 06 77 b5 c5 85 4c e6 84 71 64 b9 22 ef a2 8a 1c c4 f6 cc 16 6e 02 b5 bb 2c 3f 7d c8 a7 2a 1c 06 3b 19 4b 9a 68 8a a3 25 7e 4d 36 26 c2 ca d4 14 5f f3 5e 10 50 05 09 b9 3e 56 06 89 fd a4 71 26 fa a3 6f 19 01 49 25 95 c8 62 68 09 26 54 a0 ff 88 98 b4 2d 02 6a 11 bc b6 2a 57 55 0d 88 1c 01 7a ca 3d 6b 01 d2 52 06 7e 8f 6e f6 fd 74 af bd b4 37 e5 1c 75 cb 59 ea e5 55 4c a1 88 17 d9 61 e5 b9 02 d8 55 5e 7d 69 81 bf eb 64 fe d9 c6 9b d6 4d ba 2e 3e 84 42 a8 07 3d 3a e4 3f 74 62 92 d6 05 2f 2c 47 66 65 ff 6a 06 50 e9 9d d0 4f b8 9a c6 8b 20 b3 28 ae 56 43 46 b9 e5 f7 be b3 3d 38 a7 88 41 8a 19 72 21 90 d8 6c f4 2f ab 88 4a ad 5a ac 1e fd 9e 15 c9 a9 59 18 44 80 dd 92 3d 99 72 e8 04 b2 f9 4d c1 9d 03 ff c5 c3 79 bf 85 e0 15 65 05 9e 97 3c 01 42 92 a5 7a 8c c4 04 b3 78 67 1f be 9b 14 19 f4 78 08 5a 4a e7 c9 a5 5a 0b 76 45 22 50 fc 44 04 ba 66 f6 45 9c a7 af 8d f8 8d ee 10 9b 9d 46 65 2e 35 61 38 be e9 b4 18 37 15 76 0e 9f 12 d9 27 00 9b 1d 58 5c 45 a3 e6 f7 5c 5f 3a 68 3e 2a 5c 2a f1 d6 e2 b4 14 2e e6 62 b4 a6 2b 51 77 e1 2a 78 6f 6e 23 6c 29 4e c1 77 83 2d 8c 68 c7 56 cc e1 1e dd d0 8b 34 3d a4 8e 53 d7 19 50 80 a6 de fc 5e 7e 67 cd 26 10 5a 79 98 ae 94 ce 73 35 fd 7b 4b e4 a0 f2 9f 2a 8b df d7 15 2b b4 a6 4d 28 73 06 2b fd 6e 34 f7 c9 e2 15 53 d0 ed 31 60 ad 21 d8 b5 1a f7 36 02 e3 6e 7a 70 19 b1 4b b5 3f 5b 69 47 e3 91 27 e8 b6 71 a8 92 1f e2 b0 fa 3c fe 85 84 1a cd 93 e0 6d b9 c3 33 1c 06 20 11 a3 d5 a3 12 56 39 a4 5d 9c 23 d4 b9 30 50 38 a3 29 2a 90 3c 82 4d a9 7b 64 2a 17 b1 24 94 bd 59 9e df 66 0e 2f 2f 4c 9e 83 7f 24 79 00 32 ec 18 d1 51 ce 95 4e e1 bb bc 3d b4 43 9b 24 f2 14 9b b3 61 7a d9 6b 1f fb 32 91 2b 7e 7b 15 ff bc 0f b4 52 75 cd d7 5e e6 d8 b1 bc 1a d7 0d c1 56 b9 a2 51 9f cc aa 4f 81 14 2b 9b aa 69 18 10 d6 63 89 d1 01 bd ab 64 38 53 4c e3 18 3e 2e fc 64 63 ac 87 96 a2 5a f5 d6 ad 8e dc 92 18 be 98 70 69 de 94 5d 2e 64 84 0a 39 80 6e ee cc 07 12 6d 59 8a 23 47 29 8b 72 ae a7 23 87 ae 97 af 2c dd fa 43 9a d7 6a 30 d9 79 75 b8 35 e5 55 02 67 72 21 7c 83 31 b7 d6 95 c8 21 21 ec 27 da 9f 0c 80 67 29 16 0c cd 37 67 d4 0b f6 6e f9 59 06 5e 0e 22 aa 17 61 13 fa 06 87 92 9c 51 80 35 aa 23 a7 96 10 54 58 25 a0 b5 7c 7e e2 bb 07 30 1b d7 b4 d5 a7 a9 66 68 f8 f0 0e 66 10 f0 7b a4 3d f1 9a da d3 49 82 af d1 5d 31 17 55 3d 59 2a 1f d8 b4 84 1b dd 18 8b ff b4 c3 81 3b 53 a5 21 6f e4 9e b5 9c c8 8f d7 00 11 34 6e 8b fd af 68 22 80 18 e4 73 84 da 97 aa 59 29 21 55 9a 9d 8e e3 e2 56 9a 14 83 f1 28 ea bd 4e 22 6c fd 7e 06 25 27 7d 44 cb 2c 9c a3 54 fd 8e c1 6f e1 95 fc 57 e0 0e 7e 8c 3f 52 7a d5 69 67 d6 4d fd 4c a4 27 ce e1 a5 22 d4 5e ae ff a1 f4 61 8a 28 8e 69 cb dd c6 63 03 fa b3 cc c0 15 81 8a 2e fd 1b 42 22 b4 c9 e9 e6 c5 65 9f a0 c3 46 a9 bc 46 30 bf 65 83 9f 3a 00 ec 76 87 d6 ce b5 7b e9 08 17 5c 00 e7 e3 09 ed 1e 8d 4d 10 03 4b 2b 49 44 2f eb 41 2a be 02 1d 86 e9 c4 5c f4 d6 8a 5c ec e8 20 2f 71 f8 bb ec c0 d6 d8 f0 f7 8e 54 17 92 a1 95 77 c1 36 3a 40 6f 65 16 8a 55 f7 38 59 7b 2c 30 25 94 94 f4 ca 09 7d 6a 70 5b 52 16 24 5a 8b 33 db c3 82 51 b7 f9 a8 1c 71 1a 0c f3 b3 c1 5b 93 ]\n", stderr: "downloading crs...\nbuilding circuit...\ngates: 89992\ncomputing proving key...\ndone.\ncreating proof...\ndone.\nproof written to: /tmp/nix-shell.oZ6uW2/.tmp4ZQR7i/proof.proof\n" })
```

**Comment by TomAFrench** [comment]
Fixed in https://github.com/noir-lang/acvm-backend-barretenberg/pull/239/commits/55a64e8a82f26a2572ee319d807983f81b050fe3

**Comment by kevaundray** [comment]
This LGTM - I have created an issue in barretenberg re arm64 linux binaries since those are not outputted by bb currently

**Review by TomAFrench — APPROVED** [review]

**Pull request merged**
