### PR TITLE
chore: Document BoundedVec

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves https://github.com/noir-lang/noir/issues/4348

## Summary\*

Documents `BoundedVec`

## Documentation\*

Check one:
- [ ] No documentation needed.
- [x] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
This PR requires https://github.com/noir-lang/noir/pull/4431 for the changed `BoundedVec::new()` function

**Comment by jfecher** [comment]
Looks like this is failing due to some formatting differences in files in the stdlib that I did not touch. I'll update the PR to include them

**Comment by TomAFrench** [comment]
Can you update the examples to pull code from snippets? We can then be sure that the code in the docs is tested.

**Comment by jfecher** [comment]
Looks like re-running the tests twice fixed the issue. Third time's the charm.

**Review by TomAFrench — APPROVED** [review]
We could add more snippets here but I think this is mergeable.

**Pull request merged**
