### PR TITLE
chore(ssa refactor): Add address constants to simplify handling of addresses

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Several passes (mem2reg, acir_gen, and flattening) must deal with the issue of finding allocations and offsets of a given store or load instruction but doing so requires backtracking from the current value id usually to find a previous add instruction. From here the base allocation is often added to the desired offset being stored or loaded from and we can check if these are constant or not. This PR adds a `ReferenceConstant` value type so that this can be automatically tracked when add instructions are inserted into the SSA form.

Now when a `load value_id` is seen in SSA, we need only to check whether `value_id` refers to the result of an allocate instruction or whether it refers to a `ReferenceConstant`. When these constants are known, the IR more closely resembles a relative addressing scheme, but if they are unknown we still essentially use the addition scheme. 

Resolves 

## Summary\*

This PR sets out to

### Example

Before:

```
fn main f1 {
  b0(v1: reference):
    v2 = alloc 3 fields
    store Field 1 at v2
    v3 = add v2, Field 1
    store Field 2 at v3
    v4 = add v2, Field 2
    store Field 3 at v4
    v5 = add v2, Field 2
    v8 = load v5
    v10 = call println(v8)
    v11 = add v1, Field 5
    v12 = load v11
    v13 = call println(v12)
    return unit 0
}
```

After:

```
fn main f1 {
  b0(v1: reference):
    v2 = alloc 3 fields
    store Field 1 at v2
    store Field 2 at v2, offset 1
    store Field 3 at v2, offset 2
    v8 = load v2, offset 2
    v10 = call println(v8)
    v11 = add v1, Field 5      ; Note that if the allocation is not known, the add instruction remains.
    v12 = load v11             ; It is an open question as to whether we should consider block parameters
    v13 = call println(v12)    ; to be known.
    return unit 0
}
```

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

One may wonder why we don't just fully commit to relative indexing. I was experimenting with relative indexing a bit in the jf/ssa-relative-addresses branch but soon hit a wall in terms of handling lvalues properly - specifically for the case with nested arrays. While the branch cleaned up some handling in passes, I found handling lvalues was getting increasingly messy and soon pivoted back to this PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
This PR still needs some work and should probably be a draft. I'd still like to hear opinions on whether it is an improvement or not though.

Most notably the note `that if the allocation is not known, the add instruction remains. It is an open question as to whether we should consider block parameters to be known.` is actually not true in this current version of the PR. Block parameters will also create reference constants but this leads to a bug currently during flattening where the block parameter remains since values can now reference other values.

**Comment by kevaundray** [comment]
It would make ACIR gen easier, though reading about the edge cases created in SSA, I would be slightly hesitant to say its an overall improvement. @joss-aztec has been going over the memory abstraction in ACIR so interested to hear his thoughts

**Comment by guipublic** [comment]
Could you explain what is the problem you get with relative indexing and nested arrays?

**Comment by jfecher** [comment]
Closing this PR. I've gotten around the previous issue with relative addresses and that PR avoids ValueIds referring to other ValueIds so handling in flatten_cfg is simpler.

To elaborate on the previous problem it was having - to compile lvalues we compiled lvalues to the reference, then compiled the rhs of an assign expression, then once we had both we could go through each (lvalue, rhs) pair (since there may be multiple in the case of tuples) and create a store instruction at each address. This was not possible initially with relative indexing because we could no longer represent an offset from an address as a single ssa-gen value. I fixed it by adding the offset to Value::Mutable in that PR.

**Pull request closed without merging**
