### PR TITLE
feat: add blake3 black box function

### LINKED ISSUE #3171: Add blake3 opcode into ACIR
### Problem

Currently we have a blake2 opcode, though blake3 is considered more secure than blake2 -- it is already in the barretenberg standard library, so the added lines of code will be the same as blake2 and sha256.

### Happy Case

Add blake3 opcode into ACIR

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves #3171 

## Summary\*

This PR adds a black box function for the blake3 hash function.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by TomAFrench** [comment]
@kevaundray Do we want to push for this to get merged for kernel circuit reasons?

**Comment by kevaundray** [comment]
> @kevaundray Do we want to push for this to get merged for kernel circuit reasons?

Missed this -- this is not blocking for the kernel circuit (we just changed everything to use blake2s), though we could batch it in with https://github.com/noir-lang/noir/issues/3340

**Comment by kevaundray** [comment]
It would be good to come full circle on the blake3 issue and the hash_to_field issue too

**Comment by TomAFrench** [comment]
Closing as this PR is going to be done in the aztec-packages repo

**Pull request closed without merging**
