### PR TITLE
chore(ci): Enforce that PR titles start uppercase

### PR DESCRIPTION
**Pull request by TomAFrench**
# Related issue(s)

Resolves # 

# Description

## Summary of changes

Looking at the [changelog](https://github.com/noir-lang/noir/blob/master/CHANGELOG.md), we've got a mix of upper and lowercase first letters for each entry.

Personally I prefer commit messages/PRs starting lowercase so I have set the CI action to enforce this. Should there be strong feelings about entries in the changelog being capitalized we can also go the other way.

As an alternative, we could potentially apply some processing on release-please to format the changelog entries but from a look at their docs nothing stands out.

## Test additions / changes

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

## Documentation needs
- [ ] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

**Comment by TomAFrench** [comment]
:thinking:

**Comment by phated** [comment]
`pull_request_target` uses master as the commit the CI is run from

**Comment by TomAFrench** [comment]
> `pull_request_target` uses master as the reference the CI is run from

Ah, that makes sense.

**Comment by TomAFrench** [comment]
Looking at recent PRs it seems like people tend to prefer capitalisation here. If I switch to require this is this PR good to merge or shall I just close?

**Comment by kevaundray** [comment]
A possibly easier alternative is to use: https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#sentence-case

**Comment by kevaundray** [comment]
Tentatively closing this PR

**Pull request closed without merging**
