### PR TITLE
chore(nargo)!: use faster hash function for checking preprocessed keys

### PR DESCRIPTION
**Pull request by TomAFrench**
# Related issue(s)

Resolves https://github.com/noir-lang/noir/issues/870

# Description

## Summary of changes

We now use the faster `checksum_constraint_system` function over `hash_constraint_system` when preprocessing programs to generate their keys.

One important thing to note here is that it means that we'll be using a different hash function when saving programs to disk in comparison to the hash function we'll be using for contract functions in the A3 context. We'll need to ensure that we keep these separate. As part of that, I have updated any references to "hashes" to "checksums".

## Test additions / changes

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

## Documentation needs
- [ ] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

**Review by kevaundray — APPROVED** [review]

**Comment by TomAFrench** [comment]
Let's merge this after #1056

**Comment by kevaundray** [comment]
@TomAFrench Isn't this a breaking change?

**Comment by TomAFrench** [comment]
Making this PR breaking as the next release is a breaking release anyway.

**Comment by TomAFrench** [comment]
Hmm, I'm thinking that in combination with https://github.com/noir-lang/noir/pull/1056, this may be more trouble than its worth. If we're compiling a contract we'll want to do a sha256 hash to insert into the contract artifact so it doesn't really make sense to do another one to save to disk as a checksum.

We then can only benefit from this faster hash function for noir programs, but we'd have to have a parallel preprocessing flow for just this particular case (we can't reuse the `PreprocessedData` struct that we currently have).

I think a better route for us to follow would be for us to push more heavily for the main proving/verifying flow to be that we compile noir into a single artifact file which contains ABI, circuit, pk, vk and try to just read from this file as much as possible.

**Comment by TomAFrench** [comment]
Scratch that, I thought we were including the ACIR hash in the contract artifact.

**Comment by TomAFrench** [comment]
That said, I do think it's worth us pushing for a greater focus on having a single artifact as source of truth for programs as we do for contracts.

**Comment by kevaundray** [comment]
> That said, I do think it's worth us pushing for a greater focus on having a single artifact as source of truth for programs as we do for contracts.

Fair point -- Can you open an issue for this? The prover key can get very large, so I don't know if we want to embed it in the ABI like we do for contracts (possibly?)

**Comment by kevaundray** [comment]
For the ACIR hash, just for reference, its used only to check if the user code has changed -- We could have chosen a hash of the Noir source code or the AST, but ACIR was sort of the most convenient object to use.

**Comment by kevaundray** [comment]
> Currently yes, but I'm thinking about how we're going to be embedding the ACIR hash into the contract tree in A3. This means that in some situations we're not free to switch out the hash function for a different one (or at least it won't make sense to as we'll using sha256 as well anyway).

Hmm they are for two different purposes -- one is for checksumming the program, so the compiler can see whether we need to recompile and the other is for usage in an application

>Small terminology note, I don't think that we should refer to the structure added in https://github.com/noir-lang/noir/pull/1056 as the "contract ABI" but the "contract artifact". This matches up better with solidity (as ABI doesn't include bytecode, etc) and things can get confusing otherwise.

Thanks for the correction good ser :)

**Comment by TomAFrench** [comment]
Added an issue here #1102

> one is for checksumming the program, so the compiler can see whether we need to recompile and the other is for usage in an application

This is kind of my point with saying that we need a generic artifact. We shouldn't need to be concerned with what hash function Aztec 3 uses but it's not unlikely that the A3 artifact will contain the ACIR hash (sha256) which means we'll end up with multiple different hashes of the same data floating around for no reason.

**Comment by TomAFrench** [comment]
@kevaundray This PR should be gtg now

**Review by kevaundray — APPROVED** [review]

**Pull request merged**
