### PR TITLE
chore(docs): Updates following `is_recursive` flag removal

### PR DESCRIPTION
**Pull request by vezenovm**
# Description

## Problem\*

Followup to https://github.com/noir-lang/noir/pull/4187 for resolving #4139 

## Summary\*

We no longer need to distinguish between `generateIntermediateProof` and `generateFinalProof`. This will go into effect once https://github.com/AztecProtocol/aztec-packages/pull/4221 is merged and released.

## Documentation\*

Check one:
- [ ] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by signorecello — APPROVED** [review]
Thank you so much @vezenovm, I'll watch the other PR but I'm afraid of completely forgetting why I was watching it and forget to merge this one. Can you help me babysit them please?

**Comment by signorecello** [comment]
Maybe this one should be a draft too?

**Comment by vezenovm** [comment]
> I'll watch the other PR but I'm afraid of completely forgetting why I was watching it and forget to merge this one. Can you help me babysit them please?

Yes I will watch as well. These docs changes are due to https://github.com/AztecProtocol/aztec-packages/pull/4221 removing `generateIntermediateProof` and `generateFinalProof` just for `generateProof`.

**Comment by vezenovm** [comment]
@signorecello https://github.com/AztecProtocol/aztec-packages/pull/4221 has gone into master so I am marking this ready for review again.

**Comment by signorecello** [comment]
@vezenovm I don't see in which release will this go? Mostly so I can update noir-examples

**Comment by vezenovm** [comment]
@signorecello It looks like the PR that includes the sync is still open https://github.com/noir-lang/noir/pull/4216

**Pull request merged**
