### PR TITLE
fix: bound the number of steps in ACVM pwg

### LINKED ISSUE #5026: Recusion / AVM trace is unlimited
### Aim

I was testing a function on an edgecase, but it kept running forever.

### Expected Behavior

There should be a limit on the recursion and separately on the AVM trace length to avoid unbounded computation and draining resources.

### Bug

Computation is unbounded.

### To Reproduce

The following code allows to DoS the prover.
```rust
unconstrained fn recurse() {
        recurse();
    }
    #[test]
    fn test_recurse() {
        recurse();
    }
```
Run this test

### Project Impact

Nice-to-have

### Impact Context

_No response_

### Workaround

None

### Workaround Description

_No response_

### Additional Context

_No response_

### Installation Method

Compiled from source

### Nargo Version

nargo version = 0.29.0 noirc version = 0.29.0+b776d287db096b657e3afa12da9ae18a803a72ea (git version hash: e7e0fa5a54317e09a1c82c93c2609a688a188a88, is dirty: true)

### NoirJS Version

_No response_

### Would you like to submit a PR for this Issue?

None

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #5026

## Summary\*
This PR adds a maximum to the number of iterations for ACVM witness generation and also for the brillig VM.
As discussed, we need a maximum because loops and recursions are not bounded in brillig.

## Additional Context
The maximum is set to a high value (100 Millions), I am not sure what would be a reasonable value.

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by vezenovm** [comment]
> No, that's why I said 'resolve (?)' in the description.. The test from the issue is working fine on the mainframe and does not generate much iteration steps.

Nargo compile from the issue is not working for me?

**Comment by TomAFrench** [comment]
This PR seems to be solving a different issue compared to the issue linked.

The linked issue is related to compiling a Noir program whereas this PR places a cap on ACVM execution (which we can't get to if we're unable to compile the Noir program to ACIR).

**Comment by guipublic** [comment]
> This PR seems to be solving a different issue compared to the issue linked.
> 
> The linked issue is related to compiling a Noir program whereas this PR places a cap on ACVM execution (which we can't get to if we're unable to compile the Noir program to ACIR).

Ah yes, I the correct issue is #5026, there was a discussion on avm run limitation related to recursion so I picked the wrong issue.

**Comment by TomAFrench** [comment]
I think ideally we allow the caller to specify their own limit rather than having a hardcoded cap as that avoids us having to choose this cap and risk it being set incorrectly.

**Comment by TomAFrench** [comment]
@guipublic is this branch abandoned?

**Comment by TomAFrench** [comment]
Closing as abandoned.

**Pull request closed without merging**
