### PR TITLE
fix: Fix serialization in backend

### PR DESCRIPTION
**Pull request by kevaundray**
# Related issue(s)

Issue #1226 bundles in the change from https://github.com/noir-lang/aztec_backend/pull/145 which seems to have been the problem with the many issues we have related to the backend failing.

This PR will run the tests without the check to ensure it is failing and then pull in the changes from #1226 to see if it now passes.

Resolves # 

# Description

## Test additions / changes

# Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [ ] I have reviewed the changes on GitHub, line by line.
- [ ] I have ensured all changes are covered in the description.

## Documentation needs
- [ ] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

**Comment by kevaundray** [comment]
Still fails, going to merge in Tom's backend changes to see if it passes

**Comment by kevaundray** [comment]
It passes on ubuntu, so this was the issue -- I will now add poseidon and check if that is also fixed

**Comment by TomAFrench** [comment]
Superceded by #1226

**Comment by kevaundray** [comment]
Should have wrote [DO NOT MERGE] -- This was only intended for testing

**Pull request closed without merging**
