### PR TITLE
feat: Make arrays and slices polymorphic over each other

### LINKED ISSUE #1354: Output of `to_le_bits` doesn't work for functions that take generic array inputs
### Aim

Running the following tests causes in a panic in test1 while test2 passes

```rust
fn and<N>(bits: [u1; N]) -> u1 {
    let mut ans: u1 = 1;
    for i in 0..bits.len() {
        ans *= bits[i];
    }
    ans
}

global n = 11;

#[test]
fn test1() {
    let bits = n.to_le_bits(4);

    let ans = and(bits);
    assert(ans == 0);
}

#[test]
fn test2() {
    let tmp = n.to_le_bits(4);
    let mut bits = [0; 4];
    for i in 0..4 {
       bits[i]= tmp[i]; 
    }

    let ans = and(bits);
    assert(ans == 0);
}
```

### Expected behavior

Both tests should pass

### Bug

Error message:
```bash
Running 1 test functions...
Testing test1...
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: crates/noirc_frontend/src/monomorphization/mod.rs:729
```

### To reproduce

1. Copy the code above
2. Run `nargo test --show-output --allow-warnings test1`

### Installation method

Binary

### Nargo version

nargo 0.5.1 (git version hash: 7f6dede414c46790545b1994713d1976c5623711, is dirty: false)

### @noir-lang/noir_wasm version

_No response_

### @noir-lang/barretenberg version

_No response_

### @noir-lang/aztec_backend version

_No response_

### Additional context

_No response_

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

### LINKED ISSUE #1842: Compiler error hashing a field
### Aim

I'm new to Noir and trying to learn more about how it works.  My first example was just to attempt to hash a Field.  `nargo check` succeeds just fine, but if I attempt to actually run the test or prove, I get the below compiler error.

### Expected Behavior

The test would run and field would be hashed (or show me the error of my ways)

### Bug

```bash
$ nargo test
Running 1 test functions...
Testing test_main...
The application panicked (crashed).
Message:  invalid input
Location: crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs:184

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### To Reproduce

Try to run `nargo test` on the following circuit:

```rust
use dep::std::hash;

fn main(thing : Field) {
    let chash = hash::keccak256(thing.to_le_bytes(8));
    assert(chash[0] > 0 | chash[1] > 0);
}

#[test]
fn test_main() {
    let thing = 123;
    main(thing);
}

```

### Installation Method

Binary

### Nargo Version

nargo 0.6.0 (git version hash: 0181813203a9e3e46c6d8c3169ad5d25971d4282, is dirty: false)

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### LINKED ISSUE #1931: SSA type for loading a reference which holds a slice is seen as an array
### Aim

Trying to codegen Brillig from SSA that uses references to slices

### Expected Behavior

In the following code:
```rust
use dep::std::slice;
use dep::std;

unconstrained fn main() {
    let mut slice: [Field] = [];
    assert(slice.len() == 0);

    slice = slice.push_back(1);
    assert(slice.len() == 1);
}

```
should compile to an ssa like this one
```
// Initial SSA:
brillig fn main f0 {
  b0():
    v1 = allocate
    store [] at v1
    v3 = load v1
    v4 = call array_len(v3)
    v6 = eq v4, Field 0
    constrain v6
    v8 = load v1
    v10 = call slice_push_back(v8, Field 1)
    store v10 at v1
    v11 = load v1
    v12 = call array_len(v11)
    v13 = eq v12, Field 1
    constrain v13
    return 
}
```
Where the Value v11 has Type::Slice

### Bug

```
Type of target variable Id(11) is Array([Numeric(NativeField)], 0) for instruction Load { address: Id(1) }
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### LINKED ISSUE #1963: Change the Array/Slice subtyping relationship to a unification-based one
### Problem

When creating a slice users have to explicitly narrow the type to a slice type:
```rs
let array = [1, 2, 3];

let slice: [Field] = [1, 2, 3];
```
This is due to slices being a subtype of arrays and all array literals having an array type.

### Happy Case

If we made an array literal's size parameter polymorphic over whether it is a slice or not we would no longer need an explicit type annotation. For review, the current representation is:
```rs
type Type {
    ...
    Array { elements: Box<Type>, size: Type }, // size is expected to be a Type::Constant or generic
    Slice { elements: Box<Type> }
}
```
The proposal is to merge these two cases to something resembling:
```rs
type Type {
    ArrayOrSlice { elements: Box<Type>, size: Type }, // expected to be a Type::Constant, MaybeConstant, or generic
    MaybeConstant(u64, TypeVariable),
}
```
In this scheme an array literal `[1, 2]` would have the type:
```rs
Type::ArrayOrSlice {
    elements: Box::new(Type::Field),
    size: Type::MaybeConstant(2, TypeVariable::Unbound)
}
```
Then if the array is later used somewhere an array is expected, e.g. `fn foo(array: [Field; 2]){ ... }`, it will be narrowed to
```rs
Type::ArrayOrSlice {
    elements: Box::new(Type::Field),
    size: Type::MaybeConstant(2, TypeVariable::Bound { Type::Constant(2) })
}
```
Through normal unification. Likewise, if the type is narrowed to a slice, e.g. from `foo = foo.push_back(3)`, the type would instead be narrowed to:
```rs
Type::ArrayOrSlice {
    elements: Box::new(Type::Field),
    size: Type::MaybeConstant(2, TypeVariable::Bound { Type::SliceSize }) // where SliceSize is some arbitrary sentinel value
}
```

### Alternatives Considered

Alternatively, we could separate the syntax of arrays and slices. For example, arrays could keep the `[1, 2, 3]` syntax, and we could give slices a dedicated `&[1, 2, 3]` syntax where the `&` is part of the literal.

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves #1963
Resolves #1931
Resolves #1842
Resolves #1354

## Summary\*

Instead of representing `Type::Array(size, elem)` as a separate type from `Type::Slice(elem)` and allowing them to intermingle via subtyping, this PR removes the subtyping relationship and the `Type::Slice` variant entirely. Now, array literals have a polymorphic "MaybeConstant" size that can later be resolved to either a `Constant` size (array) or a `NotConstant` size (slice). This also means we no longer need type annotations to create slice literals.

**BREAKING CHANGES**:
~~- Arrays and slices are no longer subtypes of each other. So if you have an array and you need to pass it to a function that only accepts a slice, you now need to add an explicit `.as_slice()`.~~

- I've added an array to slice coercion so there should no longer be any breaking changes.

## Documentation

- [x] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [x] I will request for and support Dev Rel's help in documenting this PR.
    - An array literal `[a, b, c, ..]` can now resolve to either an array or a slice depending on how it is used.
    - This is just like how an integer literal can resolve to any integer type depending on how it is used.
    - Just like integer literals, if you want to convert between arrays and slices you now need an explicit conversion function.
    - Users wishing to write a function that is polymorphic over arrays and slices can still use the `fn foo<T, N>(array_or_slice: [T; N])` syntax since slices are considered to be arrays internally of a non-constant size (implementation detail).

  
  

## Additional Context

I'm putting this PR out a bit early for visibility and because I need the CI to help find which tests need a `.as_slice()` to be added.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
I think I'll try to add rust's implicit coercion of array to slice. This should no longer be a breaking change afterward.

**Comment by jfecher** [comment]
This PR is currently held up by an error in `brillig_slices`:
```
the application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: Expected array, got HeapVector(HeapVector { pointer: RegisterIndex(6), size: RegisterIndex(7) })
Location: crates/noirc_evaluator/src/brillig/brillig_gen/brillig_fn.rs:114

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 13 frames hidden ⋮                              
  14: noirc_evaluator::brillig::brillig_gen::brillig_fn::FunctionContext::extract_heap_array::h612d83e614e579d9
      at /.../noir/crates/noirc_evaluator/src/brillig/brillig_gen/brillig_fn.rs:114
  15: noirc_evaluator::brillig::brillig_gen::brillig_block::BrilligBlock::convert_ssa_value::h03347b8489e010ae
      at /.../noir/crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:803
  16: noirc_evaluator::brillig::brillig_gen::brillig_block::BrilligBlock::convert_ssa_instruction::h435b587b3c58d1e0
      at /.../noir/crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:236
  17: noirc_evaluator::brillig::brillig_gen::brillig_block::BrilligBlock::convert_block::h3079b65c1c7e2aaa
      at /.../noir/crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:61
  18: noirc_evaluator::brillig::brillig_gen::brillig_block::BrilligBlock::compile::h4903fe94bd90897c
      at /.../noir/crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:47
  19: noirc_evaluator::brillig::brillig_gen::convert_ssa_function::h6239c1d6fcb032a1
      at /.../noir/crates/noirc_evaluator/src/brillig/brillig_gen.rs:28
  20: noirc_evaluator::brillig::Brillig::compile::h3cd51d3807fe3513
      at /.../noir/crates/noirc_evaluator/src/brillig/mod.rs:28
  21: noirc_evaluator::brillig::<impl noirc_evaluator::ssa_refactor::ssa_gen::program::Ssa>::to_brillig::h58acb38d118edfdd
      at /.../noir/crates/noirc_evaluator/src/brillig/mod.rs:99
  22: noirc_evaluator::ssa_refactor::optimize_into_acir::h96fd7ea2cbc06f17
      at /.../noir/crates/noirc_evaluator/src/ssa_refactor.rs:48
  23: noirc_evaluator::ssa_refactor::create_circuit::h3221b5c03c1245cd
      at /.../noir/crates/noirc_evaluator/src/ssa_refactor.rs:81
  24: noirc_driver::compile_no_check::ha192bac6b09f9ae5
      at /.../noir/crates/noirc_driver/src/lib.rs:306
  25: noirc_driver::compile_main::h159318b5103cbeb1
      at /.../noir/crates/noirc_driver/src/lib.rs:195
  26: nargo_cli::cli::compile_cmd::compile_circuit::h750de128d64d5da7
      at /.../noir/crates/nargo_cli/src/cli/compile_cmd.rs:128
  27: nargo_cli::cli::prove_cmd::prove_with_path::hc2b46b42c1fbf6f9
      at /.../noir/crates/nargo_cli/src/cli/prove_cmd.rs:112
  28: nargo_cli::cli::prove_cmd::run::h9a42555316685c8e
      at /.../noir/crates/nargo_cli/src/cli/prove_cmd.rs:68
  29: nargo_cli::cli::start_cli::hafb3033a71756cdf
      at /.../noir/crates/nargo_cli/src/cli/mod.rs:80
  30: nargo::main::hb051dd85bb9ddb14
      at /.../noir/crates/nargo_cli/src/main.rs:14
  31: core::ops::function::FnOnce::call_once::he90185e242af6ac8
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251
                                ⋮ 13 frames hidden ⋮                              
exit 101
```
Any insight into this @sirasistant?

**Comment by sirasistant** [comment]
Yes, fixed in https://github.com/noir-lang/noir/pull/2080. The problem was that it was previously assumed that a Value::Array was always had Type::Array, which is no longer the case. Also improved a bit the brillig_slices test now that references have coherent typing!

**Review by sirasistant — APPROVED** [review]
Thanks a lot for this! :rocket:

**Comment by jfecher** [comment]
@sirasistant I've pushed an array -> slice coercion so that this is no longer a breaking change. I think this recovers the lost ergonomics as well. It works by implicitly adding a `.as_slice()` call when needed, so the backend does not have to worry about values changing types.

**Review by sirasistant — APPROVED** [review]

**Review by sirasistant — APPROVED** [review]

**Pull request merged**
