### PR TITLE
chore: document noir_wasm

### PR DESCRIPTION
**Pull request by Thunkar**
## Problem

Resolves https://github.com/noir-lang/noir/issues/4137

## Summary

Added using typedoc, better comments and improved readme.

Check one:
- [ ] No documentation needed.
- [x] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by signorecello** [comment]
Probably at this point you feel the Typedoc pain. It's a particular pain, it hits all the head homogeneously, with great intensity.

But... I'd like it to look like the other packages, which _should_ be achievable by replicating the way they're documented. 

I can pick this up, my head already stopped hurting from the Typedoc pain from a few months ago

**Review by signorecello — COMMENTED** [review]
This needs a bit more work to achieve the same formatting as the other two JS packages

**Review by signorecello — CHANGES_REQUESTED** [review]
This needs a bit more work to achieve the same formatting as the other two JS packages

**Comment by Thunkar** [comment]
@signorecello not sure what you mean by "same formatting", sorry...

I think the only difference is that I added the `README.md` on the "front page" to slightly document usage?. From what I see, types and functions use the same formatting, the only potential problem I see is that we export `CompilationResult` as a union type, but the members of said union are not exported and therefore not documented.

Please let me know, I would like to improve this!

**Review by signorecello — APPROVED** [review]
Looks great now! Thank you!

**Pull request merged**
