### PR TITLE
chore: Add `Instruction::DecrementRc`

### PR DESCRIPTION
**Pull request by jfecher**
# Description

## Problem\*

Resolves https://github.com/noir-lang/noir/issues/4522

## Summary\*

Experimenting with this to see how much it improves performance of unconstrained code using arrays.

## Additional Context

Currently the new dec_rc instruction is only issued for function parameters when a function is finished - assuming the parameters are not also returned.

CC @sirasistant for visibility

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
This seems to be a considerable improvement for pathological cases at least. Here's an example:
```rs
unconstrained fn main() {
    let mut array = [0; 10000];

    for i in 0 .. array.len() {
        array[i] = i;

        // This increments the reference count of `array` on each iteration,
        // tanking performance even though the `array2` parameter of `foo`:
        // 1. is not returned, so its lifetime should not prevent the mutation of `array`
        // 2. is not itself mutable
        foo(array);
    }
}

unconstrained fn foo<N>(_array2: [u64; N]) {}
```
On master this runs in `5m 50s` on my desktop.
On this branch, this runs in `0.67s`

**Comment by jfecher** [comment]
Not sure why the `brillig_assert_msg_runtime` test is incorrectly passing now.
I suppose the inputs are getting mangled somehow since `v73 = eq v0, Field 10` passes but `v0 = 5` in the Prover.toml.
Either that or this is skipped entirely somehow.

**Comment by sirasistant** [comment]
> Not sure why the brillig_assert_msg_runtime test is incorrectly passing now.
I suppose the inputs are getting mangled somehow since v73 = eq v0, Field 10 passes but v0 is x and x = 5 in the Prover.toml.
Either that or this is skipped entirely somehow.

Fixed it here https://github.com/noir-lang/noir/pull/4531

**Review by sirasistant — APPROVED** [review]
Let's see if we get some nice speedups!

**Comment by jfecher** [comment]
Removing this from the queue to investigate why `poseidonsponge_x5_254` blew up in size

**Comment by jfecher** [comment]
I'm still unable to find why poseidonsponge_x5_254 has bloated so much. Oddly enough, the SSA is actually shorter for the version on this branch than in master.

**Pull request merged**
