### PR TITLE
chore(ssa refactor): ACIR gen `cast` as truncate

### PR DESCRIPTION
**Pull request by joss-aztec**
# Description

## Problem\*

Cast instructions were only applying range constraints, when instead they should have been treated as truncations.

## Summary\*

ACIR gens cast instructions as truncations - skipping cast to NativeFields as a no-op.

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
Looks like we produce a proof that fails to verify for this test

**Comment by joss-aztec** [comment]
> Looks like we produce a proof that fails to verify for this test

Constraints couldn't be met because the program wasn't truncating when intended.

**Comment by joss-aztec** [comment]
(I've repurposed this PR to introduce the fix alongside the test)

**Review by jfecher — COMMENTED** [review]
Hmm I also thought the expected behavior of a cast was a range constraint

**Comment by joss-aztec** [comment]
> Hmm I also thought the expected behavior of a cast was a range constraint

@kevaundray says otherwise. The test in question only makes sense if `as` truncates.

**Review by jfecher — DISMISSED** [review]
I wasn't aware of the cast-truncate behavior and it seems a bit odd to have both casts and truncates for truncation but this PR looks fine and fixes a test, so we can worry about cleaning things up or discussing semantics at a later date.

**Pull request merged**
