### PR TITLE
chore(docs): update hashes page to pull in code

### PR DESCRIPTION
**Pull request by TomAFrench**
# Description

## Problem\*

Resolves https://github.com/noir-lang/noir/issues/4176

## Documentation\*

Check one:
- [ ] No documentation needed.
- [x] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by critesjosh — APPROVED** [review]

**Comment by Savio-Sou** [comment]
Thank you @TomAFrench!

Would the use of `#include_code` work as intended when docs are cut into `versioned_docs`?

As in for example if `#include_code` is used in `versioned_docs/version-v0.23.0`, would it pull code at v0.23.0's commit instead of from the latest master?

**Comment by TomAFrench** [comment]
Not perfectly.

The way it works is that on the release PR, we'll generate a version in `versioned_docs` with the snippets resolved to the code as of the release PR. The markdown is then frozen with the content as of that commit (i.e. we don't codegen for versioned docs after when the version is cut), the links however will still point towards master and so will become stale over time.

We could modify this so that the links point towards the release tag however in future.

**Comment by Savio-Sou** [comment]
Clarification appreciated. Will make sure to copy content rather than codegen for the retro additions into v0.23.0 in that case.

**Comment by signorecello** [comment]
Yep those retro additions wouldn't be codegen-ed anyway so the page would look terrible 😊 so it's hard to make a mistake there

**Pull request merged**
