### PR TITLE
fix: pub is required on return for entry points

### LINKED ISSUE #3344: contract_library_method's should not require a pub return type
### Aim

The following code should compile, since the `contract_library_method` attribute specifies that the method will not be used as an entry point function.

```rust
contract Foo {
    #[contract_library_method]
    fn foo(x : u8) -> u8 {
        x
    }
}
```

### Expected Behavior

.

### Bug

Instead of it passing, we get:

```
error: missing pub keyword on return type of function foo2
   ┌─ main.nr:14:8
   │
14 │     fn foo(x : u8) -> u8 {
   │        ---- missing pub on return type
   │
   = The `pub` keyword is mandatory for the entry-point function return type because the verifier cannot retrieve private witness and thus the function will not be able to return a 'priv' value

Aborting due to 1 previous error
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Nargo Version

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by guipublic**
# Description

## Problem\*

Resolves #3344 and #3632

## Documentation\*

Check one:
- [X] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[Exceptional Case]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [X ] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Review by jfecher — CHANGES_REQUESTED** [review]
As it is now, `contract_library_method`s would be allowed to use `pub` parameters even though they are not entry points. I think we should update the definition of `pub_allowed` instead of removing it entirely.

**Comment by guipublic** [comment]
> As it is now, `contract_library_method`s would be allowed to use `pub` parameters even though they are not entry points. I think we should update the definition of `pub_allowed` instead of removing it entirely.

I did not remove entirely `pub_allowed`, `pub_allowed` is about the function parameters so for me it is normal to not use it for the return visibility.
The issue is about the return value, if there is another issue with the parameters, we should either create a new one or update this one.

**Comment by jfecher** [comment]
@guipublic https://github.com/noir-lang/noir/issues/3632

**Comment by kevaundray** [comment]
The reason we wanted to remove pub on the return type is because its not an entry-point function, the same reason also applies for pub in the function parameter.

Lets fix https://github.com/noir-lang/noir/issues/3632 alongside this since they are releated and stem from the same underlying thesis

**Comment by kevaundray** [comment]
@jfecher can you re-review?

**Review by jfecher — APPROVED** [review]

**Pull request merged**
