### PR TITLE
chore(deps): Update bb_wrapper to disable ASM instructions

### PR DESCRIPTION
**Pull request by phated**
# Related issue(s)

Resolves # 

# Description

This updates to the latest `barretenberg_wrapper` commit, where I disabled the ASM instructions inside of barretenberg. I want to see if we can avoid the `illegal instruction` CI failures that we see a lot. This is hopefully just a workaround until we can depend on upstream bb (and can ask them to fix it if still broken).

@TomAFrench Can you test this change against your problem in #675?

Since I used `cargo update` to get the new version, I also committed the rest of the dependencies it suggested we bump.

## Test additions / changes

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.
- [ ] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

**Comment by TomAFrench** [comment]
I'm still getting invalid instructions off of [2b51105](https://github.com/noir-lang/noir/pull/792/commits/2b5110538d44a597f6ea085ffbd6b427229fc170) after making sure to clear out the old installation unfortunately :(

**Comment by kevaundray** [comment]
> I'm still getting invalid instructions off of [2b51105](https://github.com/noir-lang/noir/pull/792/commits/2b5110538d44a597f6ea085ffbd6b427229fc170) after making sure to clear out the old installation unfortunately :(

Are you able to reliably reproduce?

**Comment by phated** [comment]
That really doesn't make sense. How are you clearing out the old installation?

**Comment by TomAFrench** [comment]
Yeah, it happens on every interaction with the backend.

> That really doesn't make sense. How are you clearing out the old installation?

I deleted the `nargo` bin and reinstalled, I ended up recompiling all of the dependencies due to the changes here. I'm going to do a full scorched earth install (deleting the whole `.nargo` dir and `cargo clean`)

**Comment by TomAFrench** [comment]
Same thing unfortunately.

**Comment by phated** [comment]
@TomAFrench Cargo also caches git repos in `.cargo/git/checkouts/` so you probably need to remove that **and** do a `cargo clean`

**Comment by phated** [comment]
I'm also curious on your `which nargo` since I know you juggle a lot of different nargo installs

**Comment by TomAFrench** [comment]
> Cargo also caches git repos in .cargo/git/checkouts/ so you probably need to remove that and do a cargo clean

Done and same issue I'm afraid :(

> I'm also curious on your which nargo since I know you juggle a lot of different nargo installs

This is `/home/tom/.nargo/bin/nargo`, if I delete that then bash can't find any other installs of nargo. I make sure to only install through noirup to avoid this.

**Comment by phated** [comment]
> This is /home/tom/.nargo/bin/nargo, if I delete that then bash can't find any other installs of nargo. I make sure to only install through noirup to avoid this.

Please use `cargo install --path crates/nargo`. I'm starting to get the feeling that source builds in noirup aren't working.

**Comment by phated** [comment]
It seems that native builds in noirup set `RUSTFLAGS="-C target-cpu=native"` which I've never seen and could very-well be the problem you are seeing.

**Comment by TomAFrench** [comment]
I think I remember stripping those out and having the same issue. Testing now though.

**Comment by TomAFrench** [comment]
No luck sadly, I've built this branch with `cargo install --path crates/nargo` and still get `Illegal instruction (core dumped)` when proving `1_mul`.

**Comment by kevaundray** [comment]
@TomAFrench since there were no adverse affects of diabling the ASM, we were going to test it on the CI to see if it stops giving us Illegal Instruction.

**Comment by phated** [comment]
@kevaundray this still needs an approval

**Review by kevaundray — APPROVED** [review]

**Pull request merged**
