### PR TITLE
chore: Compile ssa refactor test vectors

### LINKED ISSUE #2020: Create ACIR + witness artifacts for Barretenberg using `experimental-ssa`
### Problem

Barretenberg uses the committed ACIR and witness files in the `test_data` directory in order to test ACIR proof generation. As we switch over to using the new SSA by default we want to ensure that Barretenberg has test coverage for this.

### Happy Case

We should run the `rebuild.sh` script on the `test_data_ssa_refactor` directory and update Barretenberg to pull these and run its tests on them.

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_

### PR DESCRIPTION
**Pull request by kevaundray**
# Description

## Problem\*

Resolves #2020 

## Documentation

- [ ] This PR requires documentation updates when merged.

  

  - [ ] I will submit a noir-lang/docs PR.

  

  - [ ] I will request for and support Dev Rel's help in documenting this PR.

  
  

## Additional Context

# PR Checklist\*

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by kevaundray** [comment]
Note: These were not compiled using `--flat-witness` config flag

**Review by jfecher — APPROVED** [review]
I definitely went through and reviewed each line manually

**Comment by kevaundray** [comment]
Running these against barretenberg!

**Comment by kevaundray** [comment]
I have created this branch in bb which is passing except for `9_conditional` since all except one tests pass, its likely not a problem with the serialization of these files and a problem elsewhere, so merging

**Comment by kevaundray** [comment]
Branch is here: https://github.com/AztecProtocol/barretenberg/pull/626

**Pull request merged**
