### PR TITLE
feat: implement LSP code action "Implement missing members"

### PR DESCRIPTION
**Pull request by asterite**
# Description

## Problem

Part of #1579

## Summary

Adds a code action to add missing trait impl methods and types. Default methods are not includeded.

Here it's working for `Add`:
lsp-implement-missing-members-add

Here for `BigField`:
lsp-implement-missing-members-big-field

Here for a complex type in Aztec-Packages:
lsp-implement-missing-members-aztec

## Additional Context

I found this code action in Rust very useful! It saves a lot of time, plus there's no need to copy-paste :-)

## Documentation

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
@asterite does this work for generic traits as well?

**Comment by asterite** [comment]
Indeed!

lsp-implement-missing-members-generics

There's also a test for this:

https://github.com/noir-lang/noir/pull/6020/files#diff-64550f4430118c075e6a502dcfab82391db65aab2ddfd1c27db0d0b308018ff6R724-R755

That said, it's possible I forgot to handle some cases... but we can fix those cases as they happen.

**Comment by asterite** [comment]
Here's another one, with associated types:

lsp-implement-missing-members-more-generics

**Review by jfecher — APPROVED** [review]
Great!

I was just trying to reach for this today with the Hash/Eq PR.

**Comment by asterite** [comment]
> I was just trying to reach for this today with the Hash/Eq PR.

All good. I just realized that I didn't ask for a review, so I did it :-)

**Comment by asterite** [comment]
> All good. I just realized that I didn't ask for a review, so I did it :-)

Ah, ignore me, I misunderstood what you said 😅

**Pull request merged**
