### PR TITLE
Update barretenberg wrapper dependency

### PR DESCRIPTION
**Pull request by kevaundray**

### CODE REVIEW

**Comment by jfecher** [comment]
What changes does this dependency have?

**Comment by kevaundray** [comment]
Main changes are that it updates gtest, googlebenchmarks and removes the WFatalError and Werror flags.

These flags are cause the build to fail when a user uses an upgraded version of clang/gcc and the newer version includes additional warnings.

**Comment by guipublic** [comment]
Shouldn't you use https://github.com/AztecProtocol/aztec-connect/tree/master/barretenberg repository?

**Comment by kevaundray** [comment]
That is the repo being used, it just points to a commit hash on a different branch

**Comment by guipublic** [comment]
could you send the link to the branch (I don't know how to find it from the rev number)?

**Comment by kevaundray** [comment]
The rev number is the commit hash, you can find the delta of the commits here: https://github.com/AztecProtocol/barretenberg/commits/657ba943be2c4858e61628b3dd7189b793453d8e

**Review by jfecher — APPROVED** [review]

**Pull request merged**
