### PR TITLE
chore: moving ordering to category jsons and frontmatters

### PR DESCRIPTION
**Pull request by signorecello**
# Description

This big PR does a simple thing: It makes pages ordering respect metadata instead of filenames

## Problem\*

A naive approach supported over the years at docusaurus was to simply have files prefixed with 00, 01, 02, which were removed automatically by docusaurus.

This makes docs a bit harder to maintain if for some reason you decide to move pages around, as it breaks all the links.

## Summary\*

- Renames all the folders and pages to remove the prefixes
- Adds `sidebar_position` property in frontmatter, to order them 
- Adds `_category_.json` files to order folders
- Removes ordering of top level folders in `sidebars.json`

### CODE REVIEW

**Review by TomAFrench — APPROVED** [review]
Gonna trust that all the links have been updated (does docusaurus check this automatically?)

**Comment by signorecello** [comment]
@Savio-Sou my friend in PR reviews (and more) here's the PR to reorder stuff without prefixes as suggested in the docusaurus docs for v3

**Comment by signorecello** [comment]
Yes @TomAFrench it will fail to build if there are dead links 👍

**Comment by f01dab1e** [comment]
After clicking on 'Try it now!', the following error occurs:
```
Uncaught (in promise) TypeError: super is not a constructor
    _j https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/1800.f7096443.js:2
    $j https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/1800.f7096443.js:2
    V_ https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/1800.f7096443.js:2
    u_ https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/1800.f7096443.js:2
    _createInstance https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/1800.f7096443.js:2
    createInstance https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/1800.f7096443.js:2
    __ https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/1800.f7096443.js:2
    ckA https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/1800.f7096443.js:2
    ckA https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/1800.f7096443.js:2
    ac https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/main.5d9bea90.js:2
    wl https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/main.5d9bea90.js:2
    kl https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/main.5d9bea90.js:2
    k https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/main.5d9bea90.js:2
    A https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/main.5d9bea90.js:2
[1800.f7096443.js:2:14780460](https://657854b8cf0a0159297cfd1b--noir-docs.netlify.app/assets/js/1800.f7096443.js)
​```

**Comment by signorecello** [comment]
glad you were the only one actually clicking the preview haha I'll have a look, thanks Kev

**Comment by kevaundray** [comment]
> glad you were the only one actually clicking the preview haha I'll have a look, thanks Kev

Thats not me ser :)

**Comment by signorecello** [comment]
oh damn your avatars are too similar 😄 fixed that regression @f01dab1e , somehow introduced in #3711 . Still waiting for the next docusaurus to bump webpack version, to avoid this stupid workaround

**Pull request merged**
