### PR TITLE
feat: Consider block parameters in variable liveness

### PR DESCRIPTION
**Pull request by sirasistant**
# Description

## Problem\*

Previously, on variable liveness we completely ignored block parameters, by allocating all the parameters of all blocks at the start of the function codegen and maintaining them allocated for the whole function. 

## Summary\*

With this change, we add a definition point for block parameters and we start considering them and allocating and freeing them dynamically. This should save space in the stack, especially in heavily inlined functions with many blocks.

## Documentation\*

Check one:
- [x] No documentation needed.
- [ ] Documentation included in this PR.
- [ ] **[For Experimental Features]** Documentation to be submitted in a separate PR.

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jfecher** [comment]
Is there a code example that prompted this? I'm interested to see how much this affects performance aside from memory usage if at all

**Comment by TomAFrench** [comment]
Agree that a test case would be good to have for this.

**Comment by sirasistant** [comment]
> Agree that a test case would be good to have for this.
I added a unit test for this but I'm not sure how can I do an e2e test for this given the current test infrastructure, unless I create a huge noir file with thousands of if statements

**Comment by sirasistant** [comment]
@jfecher @TomAFrench added a test that breaks in nightly and is fixed by this feature. I created a huge data structure and 5 if-else blocks to go over the 2048 stack items limit.

**Comment by sirasistant** [comment]
@TomAFrench Seems like I no longer have have merge permissions

**Comment by TomAFrench** [comment]
Huh, that's odd. I'll take a look at it

**Pull request merged**
