### PR TITLE
Remove dbg macro instances

### LINKED ISSUE #599: Remove dbg! statements in code
# Problem

dbg! statements should not be in the code, especially since we are publishing in release mode. They are fine for debugging errors etc, but ideally should not be committed.

# Solution

CTRL+F "dbg!" and remove/refactor the usage of dbg!

# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

(If applicable.)

### PR DESCRIPTION
**Pull request by jfecher**
# Related issue(s)

Resolves #599

# Description

## Summary of changes

Removes every instance of the `dbg!` macro

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

### CODE REVIEW

**Review by vezenovm — COMMENTED** [review]
Looks good. Just one comment. With your addition of `try_range_constraint` could you remove anywhere where we just unwrap on the `range_constraint` call? I know it is being done [here](https://github.com/noir-lang/noir/blob/f5d04f1ec406cb7325de8f81497c7861b89b3a48/crates/noirc_evaluator/src/ssa/acir_gen.rs#L660). Not sure if there is any other spots

**Comment by jfecher** [comment]
I went ahead and replaced that instance with try_range_constraint as well. After searching with ripgrep there aren't any other instances of unwrapping a range constraint. There are a few instances in evaluator/lib.rs which propagate the error via `?`, I chose to leave these alone.

**Review by vezenovm — APPROVED** [review]

**Comment by kevaundray** [comment]
Looks good. Next time, let's try to be strict about what changes are added to the PR. Ie the try_range_constraint is out of scope for the issue being resolved. 

There will be exceptions to this rule where the change is so minute that it may not matter, like fixing a comment around the debug.

In this case, I probably would have opened up an issue and checked if there are other places where this code style will need to be refactored out in ssa

**Comment by jfecher** [comment]
I don't think adding `try_range_constraint` was out of scope. I consider it a minor change like adding a comment since it is a 1 line wrapper function to replace a repeated pattern that needed fixing up anyway for this change. I mentioned before but I ripgrep'd the codebase already to make sure there were no other instances of range_constraint that were missed. Perhaps we want to investigate further how often acir_gen unwraps or immediately prints errors and continues in general in pursuit of a more consistent error handling strategy. I'd certainly consider that out of scope for this PR and we can open an issue for that if it is desired. I'll also make sure to keep in mind whether a change is out of scope for other PRs in the future.

**Pull request merged**
