### PR TITLE
chore(ci): remove nightly builds and run tests only on stable Rust 

### PR DESCRIPTION
**Pull request by kevaundray**
# Related issue(s)

# Description

- We want to build the compiler on a stable version of Rust, whereas nightly has no stable guarantees.
- If we introduce a nightly only feature, we will need to feature gate it as it would break the stable release which is something we don't plan to do for the foreseeable future.

## Test additions / changes

# Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [ ] I have reviewed the changes on GitHub, line by line.
- [ ] I have ensured all changes are covered in the description.
- [ ] This PR requires documentation updates when merged.

# Additional context

### CODE REVIEW

**Review by phated — APPROVED** [review]
Discussed on slack. I think this makes sense and I can propagate to the shared workflows too

**Comment by phated** [comment]
@kevaundray you'll want to remove the check that it's trying to find for nightly

**Comment by kevaundray** [comment]
> @kevaundray you'll want to remove the check that it's trying to find for nightly

Which check are you refering to?

**Comment by phated** [comment]
@kevaundray it looks like there are 2 checks that claim to be required but aren't running because you are removing them?
```
check_n_test (nightly) Expected — Waiting for status to be reported (Required)
check_n_test (stable) Expected — Waiting for status to be reported  (Required)
```
I think they might be required checks applied to your `kw/*` branch protection (do we still need those?)

**Comment by kevaundray** [comment]
> @kevaundray it looks like there are 2 checks that claim to be required but aren't running because you are removing them?
> 
> ```
> check_n_test (nightly) Expected — Waiting for status to be reported (Required)
> check_n_test (stable) Expected — Waiting for status to be reported  (Required)
> ```
> 
> I think they might be required checks applied to your `kw/*` branch protection (do we still need those?)

Oh good catch -- I've removed them

**Pull request merged**
