### PR TITLE
implement `+=`, `-=`, `*=`, `/=`, `%=`

### PR DESCRIPTION
**Pull request by Ethan-000**
# Related issue(s)

Ref https://github.com/noir-lang/noir/issues/616

# Description

Try resolve 616

## Test additions / changes

# Checklist

- [ ] I have tested the changes locally.
- [ ] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [ ] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [ ] I have reviewed the changes on GitHub, line by line.
- [ ] I have ensured all changes are covered in the description.

# Additional context

### CODE REVIEW

**Comment by Ethan-000** [comment]
I don't know how to desugar these in the parser sir :sob:, probably need some help @kevaundray @jfecher

**Comment by jfecher** [comment]
I'll branch off this locally then make a PR to merge into this branch when I've added the parsing additions

**Comment by jfecher** [comment]
I wasn't able to target this branch for the merge, so I've targetted master in the new PR instead. You can find it here: https://github.com/noir-lang/noir/pull/695. I've made sure to include your original commit still.

Closing this PR since it is superceded by 695

**Comment by Ethan-000** [comment]
Thanks for the help sir 🙂.

**Comment by Ethan-000** [comment]
feel free to delete or add anything. I'm not sure if I did things correctly

**Pull request closed without merging**
